/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Clases.Arbol;
import Clases.ColaConPrioridad;
import Clases.Denuncia;
import Clases.Lista;
import Clases.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rosco
 */
public class cambiarDisponibilidad extends javax.swing.JPanel {

    Usuario usu = new Usuario();
    Lista lt = new Lista();
    Denuncia denuncia = new Denuncia();
    Arbol denuncias = new Arbol();
    DefaultListModel dlm = new DefaultListModel();
    ColaConPrioridad colacpusu = new ColaConPrioridad();
    ColaConPrioridad colatotal = new ColaConPrioridad();
    ColaConPrioridad colaabg = new ColaConPrioridad();

    /**
     * Creates new form Princ
     */
    public cambiarDisponibilidad() {
        initComponents();
        imagenEnProceso.setVisible(false);
        imagenOcupado.setVisible(false);
        imagenDisponible.setVisible(true);
        lbldisponibilidadActual.setText("Disponibilidad actual:" + usu.getDisponibilidad());
        /*jListAbogados.setModel(dlm);
        ArrayList<Denuncia> listado = colatotal.obtenerTodos();

        Collections.sort(listado);
        for (Denuncia obj : listado) {
            dlm.addElement(obj.toString());
        }*/
    }

    public void Listar1(String tipo) {
        dlm.removeAllElements();
        for (Usuario asuarioab : lt.getComponente()) {
            if (tipo.equals(asuarioab.getTipo())) {
                dlm.addElement(asuarioab.toStringAbg());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbldisponibilidadActual = new javax.swing.JLabel();
        imagenDisponible = new javax.swing.JLabel();
        btnCambiarDisponibilidad = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbldisponibilidadActual1 = new javax.swing.JLabel();
        cmbCambiarDisponibilidad = new javax.swing.JComboBox<>();
        imagenOcupado = new javax.swing.JLabel();
        imagenEnProceso = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        Title.setText("Cambiar Disponibilidad");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Bienvenido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Aqui puedes cambiar tu disponibilidad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        btnMostrar.setBackground(new java.awt.Color(18, 90, 173));
        btnMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrarMousePressed(evt);
            }
        });
        btnMostrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ver");
        btnMostrar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 160, 50));

        lbldisponibilidadActual.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbldisponibilidadActual.setText("Disponibilidad actual:");
        jPanel1.add(lbldisponibilidadActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        imagenDisponible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/business_application_addmale_useradd_insert_add_user_client_2312.png"))); // NOI18N
        jPanel1.add(imagenDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        btnCambiarDisponibilidad.setBackground(new java.awt.Color(18, 90, 173));
        btnCambiarDisponibilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiarDisponibilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiarDisponibilidadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCambiarDisponibilidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCambiarDisponibilidadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCambiarDisponibilidadMousePressed(evt);
            }
        });
        btnCambiarDisponibilidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cambiar");
        btnCambiarDisponibilidad.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(btnCambiarDisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 160, 50));

        lbldisponibilidadActual1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbldisponibilidadActual1.setText("Cambiar disponibilidad: ");
        jPanel1.add(lbldisponibilidadActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        cmbCambiarDisponibilidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "En proceso", "Ocupado" }));
        jPanel1.add(cmbCambiarDisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 252, 140, 40));

        imagenOcupado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete_delete_deleteusers_delete_male_user_maleclient_2348.png"))); // NOI18N
        jPanel1.add(imagenOcupado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        imagenEnProceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/businessapplication_edit_male_user_thepencil_theclient_negocio_2321.png"))); // NOI18N
        jPanel1.add(imagenEnProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseClicked
        // TODO add your handling code here:
        MenuAbogado mA = new MenuAbogado();

        //den = new Denuncia((String)cmbCaracter.getSelectedItem(),(String)cmbInstancia.getSelectedItem(),(String)cmbAsistencia.getSelectedItem(),txtResponsables.getText(),txtHechos.getText());
        //colacpusu.encolar(new Denuncia((String) cmbCaracter.getSelectedItem(), (String) cmbAsistencia.getSelectedItem(), (String) cmbAsistencia.getSelectedItem(), txtResponsables.getText(), txaCarta.getText(), usu.getCedula(), gravedad, "En revision"));
        //colatotal.encolar(new Denuncia((String) cmbCaracter.getSelectedItem(), (String) cmbAsistencia.getSelectedItem(), (String) cmbAsistencia.getSelectedItem(), txtResponsables.getText(), txaCarta.getText(), usu.getCedula(), gravedad, "En revision"));
        //usu.setColaden(colacpusu);
        if (usu.getDisponibilidad().equals("Disponible")) {
            usu.setDisponibilidad("Disponible");
            lbldisponibilidadActual.setText("Disponibilidad actual:" + usu.getDisponibilidad());
            imagenEnProceso.setVisible(false);
            imagenOcupado.setVisible(false);
            imagenDisponible.setVisible(true);
        } else if (usu.getDisponibilidad().equals("En proceso")) {
            lbldisponibilidadActual.setText("Disponibilidad actual:" + usu.getDisponibilidad());
            imagenEnProceso.setVisible(true);
            imagenOcupado.setVisible(false);
            imagenDisponible.setVisible(false);
        } else if (usu.getDisponibilidad().equals("Ocupado")) {
            lbldisponibilidadActual.setText("Disponibilidad actual:" + usu.getDisponibilidad());
            imagenEnProceso.setVisible(false);
            imagenOcupado.setVisible(true);
            imagenDisponible.setVisible(false);
        }

        mA.usu = usu;
        mA.lt = lt;
        mA.denuncia = denuncia;
        mA.denuncias = denuncias;
        mA.colacpusu = colacpusu;
        mA.colatotal = colatotal;

        //txaDenuncias.setText(denuncias.mo);
        //Listar();

    }//GEN-LAST:event_btnMostrarMouseClicked

    private void btnMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseEntered
        setColor(btnMostrar);
    }//GEN-LAST:event_btnMostrarMouseEntered

    private void btnMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseExited
        resetColor(btnMostrar);
    }//GEN-LAST:event_btnMostrarMouseExited

    private void btnMostrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMousePressed

    }//GEN-LAST:event_btnMostrarMousePressed

    private void btnCambiarDisponibilidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarDisponibilidadMouseClicked
        // TODO add your handling code here:
        MenuAbogado mA = new MenuAbogado();
        String tipoDisp = (String) cmbCambiarDisponibilidad.getSelectedItem();
        if (tipoDisp.equals("Disponible")) {
            usu.setDisponibilidad("Disponible");
            lbldisponibilidadActual.setText("Disponibilidad actual:" + usu.getDisponibilidad());
            imagenEnProceso.setVisible(false);
            imagenOcupado.setVisible(false);
            imagenDisponible.setVisible(true);
        } else if (tipoDisp.equals("En proceso")) {

            usu.setDisponibilidad("En proceso");
            lbldisponibilidadActual.setText("Disponibilidad actual:" + usu.getDisponibilidad());
            imagenEnProceso.setVisible(true);
            imagenOcupado.setVisible(false);
            imagenDisponible.setVisible(false);
        } else if (tipoDisp.equals("Ocupado")) {
            usu.setDisponibilidad("Ocupado");
            lbldisponibilidadActual.setText("Disponibilidad actual:" + usu.getDisponibilidad());
            imagenEnProceso.setVisible(false);
            imagenOcupado.setVisible(true);
            imagenDisponible.setVisible(false);
        }
        mA.usu = usu;
        mA.lt = lt;
        mA.denuncia = denuncia;
        mA.denuncias = denuncias;
        mA.colacpusu = colacpusu;
        mA.colatotal = colatotal;
    }//GEN-LAST:event_btnCambiarDisponibilidadMouseClicked

    private void btnCambiarDisponibilidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarDisponibilidadMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarDisponibilidadMouseEntered

    private void btnCambiarDisponibilidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarDisponibilidadMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarDisponibilidadMouseExited

    private void btnCambiarDisponibilidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarDisponibilidadMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarDisponibilidadMousePressed

    void setColor(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel btnCambiarDisponibilidad;
    private javax.swing.JPanel btnMostrar;
    private javax.swing.JComboBox<String> cmbCambiarDisponibilidad;
    private javax.swing.JLabel imagenDisponible;
    private javax.swing.JLabel imagenEnProceso;
    private javax.swing.JLabel imagenOcupado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbldisponibilidadActual;
    private javax.swing.JLabel lbldisponibilidadActual1;
    // End of variables declaration//GEN-END:variables
}
