/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Clases.Arbol;
import Clases.ColaConPrioridad;
import Clases.Denuncia;
import Clases.Lista;
import Clases.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rosco
 */
public class CitaGerencia extends javax.swing.JPanel {

    Usuario usu = new Usuario();
    Lista lt = new Lista();
    Denuncia denuncia = new Denuncia();
    Arbol denuncias = new Arbol();
    DefaultListModel dlm = new DefaultListModel();
    ColaConPrioridad colacpusu = new ColaConPrioridad();
    ColaConPrioridad colatotal = new ColaConPrioridad();
    ColaConPrioridad colaabg = new ColaConPrioridad();

    /**
     * Creates new form Princ
     */
    public CitaGerencia() {
        initComponents();
        /*jListAbogados.setModel(dlm);
        ArrayList<Denuncia> listado = colatotal.obtenerTodos();

        Collections.sort(listado);
        for (Denuncia obj : listado) {
            dlm.addElement(obj.toString());
        }*/
    }

    public void Listar1(String tipo) {
        dlm.removeAllElements();
        for (Usuario asuarioab : lt.getComponente()) {
            if (tipo.equals(asuarioab.getTipo())) {
                dlm.addElement(asuarioab.toStringAbg());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGenerarCita = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbldisponibilidadActual1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        Title.setText("Cita gerencia");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Llena los campos un correo electronico te llegara cuando");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("el presidente se encuentre disponible");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        btnGenerarCita.setBackground(new java.awt.Color(18, 90, 173));
        btnGenerarCita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarCitaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarCitaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarCitaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGenerarCitaMousePressed(evt);
            }
        });
        btnGenerarCita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Generar Cita");
        btnGenerarCita.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(btnGenerarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 160, 50));

        lbldisponibilidadActual1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbldisponibilidadActual1.setText("Ingresa el motivo de tu cita:");
        jPanel1.add(lbldisponibilidadActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 410, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarCitaMouseClicked
        // TODO add your handling code here:
        MenuAbogado mA = new MenuAbogado();
        JOptionPane.showMessageDialog(null, "CITA GENERADA CORRECTAMENTE \n ESPERA EL CORREO DE CONFIRMACION");
        mA.usu = usu;
        mA.lt = lt;
        mA.denuncia = denuncia;
        mA.denuncias = denuncias;
        mA.colacpusu = colacpusu;
        mA.colatotal = colatotal;
    }//GEN-LAST:event_btnGenerarCitaMouseClicked

    private void btnGenerarCitaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarCitaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarCitaMouseEntered

    private void btnGenerarCitaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarCitaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarCitaMouseExited

    private void btnGenerarCitaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarCitaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarCitaMousePressed

    void setColor(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel btnGenerarCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbldisponibilidadActual1;
    // End of variables declaration//GEN-END:variables
}
