/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Clases.Arbol;
import Clases.ColaConPrioridad;
import Clases.Denuncia;
import Clases.Lista;
import Clases.Usuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rosco
 */
public class DenunciaUsuario extends javax.swing.JPanel {

    Usuario usu = new Usuario();
    Lista lt = new Lista();
    Denuncia denuncia = new Denuncia();
    Arbol denuncias = new Arbol();
    DefaultListModel dlm = new DefaultListModel();
    ColaConPrioridad colacpusu = new ColaConPrioridad();
    ColaConPrioridad colatotal = new ColaConPrioridad();

    /**
     * Creates new form Princ
     */
    public DenunciaUsuario() {
        initComponents();
        cmbInstancia.setEnabled(false);
        cmbAsistencia.setEnabled(false);
        txtResponsables.setEnabled(false);
        txaCarta.setEnabled(false);
    }

    public void Listar() {
        dlm.removeAllElements();
        //dlm.addElement(denuncias.preOrden());
    }

    void setColor(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }

    public boolean verificarVacio(String texto) {
        return texto.isEmpty();
    }
    static String getRandomString(int i) 
    { 
    
        // bind the length 
        byte[] bytearray;
        bytearray = new byte[256];         
        String mystring;
        StringBuffer thebuffer;
        String theAlphaNumericS;

        new Random().nextBytes(bytearray); 

        mystring 
            = new String(bytearray, Charset.forName("UTF-8")); 
            
        thebuffer = new StringBuffer();
        
        //remove all spacial char 
        theAlphaNumericS 
            = mystring 
                .replaceAll("[^A-Z0-9]", ""); 

        //random selection
        for (int m = 0; m < theAlphaNumericS.length(); m++) { 

            if (Character.isLetter(theAlphaNumericS.charAt(m)) 
                    && (i > 0) 
                || Character.isDigit(theAlphaNumericS.charAt(m)) 
                    && (i > 0)) { 

                thebuffer.append(theAlphaNumericS.charAt(m)); 
                i--; 
            } 
        } 

        // the resulting string 
        return thebuffer.toString(); 
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbCaracter = new javax.swing.JComboBox<>();
        cmbAsistencia = new javax.swing.JComboBox<>();
        cmbInstancia = new javax.swing.JComboBox<>();
        txtResponsables = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaCarta = new javax.swing.JTextArea();
        btnIngresar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        Title.setText("Crear Denuncia");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Text1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Text1.setText("Caracter de la denuncia: ");
        jPanel1.add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Instancia de la denuncia:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Asistencia Personal del CIDHU:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Ingrese el nombre de los ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        cmbCaracter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Familiar", "Organizacion", "Asociacion", "Institucion", "Grupo", "Empresa", "Estado", "Gobierno Autonomo" }));
        cmbCaracter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCaracterActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCaracter, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 160, 30));

        cmbAsistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));
        cmbAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAsistenciaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 160, 30));

        cmbInstancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Territorial", "Nacional", "Internacional" }));
        cmbInstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbInstanciaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbInstancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 160, 30));
        jPanel1.add(txtResponsables, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 280, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("responsables/autoridad u Institucion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Ingrese una sintesis de los hechos:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txaCarta.setColumns(20);
        txaCarta.setRows(5);
        jScrollPane1.setViewportView(txaCarta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 490, 210));

        btnIngresar.setBackground(new java.awt.Color(18, 90, 173));
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnIngresarMousePressed(evt);
            }
        });
        btnIngresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ingresar");
        btnIngresar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        // TODO add your handling code here:
        MenuUsuario mn = new MenuUsuario();
        String random = getRandomString(5);
        int gravedad = denuncia.algoritmoAnaliticoBusquedaPalabrasClave(txaCarta.getText());
        if (!verificarVacio(txaCarta.getText()) && !verificarVacio(txtResponsables.getText())) {
            //den = new Denuncia((String)cmbCaracter.getSelectedItem(),(String)cmbInstancia.getSelectedItem(),(String)cmbAsistencia.getSelectedItem(),txtResponsables.getText(),txtHechos.getText());
            colacpusu.encolar(new Denuncia((String) cmbCaracter.getSelectedItem(), (String) cmbInstancia.getSelectedItem(), (String) cmbAsistencia.getSelectedItem(), txtResponsables.getText(), txaCarta.getText(), usu.getCedula(), gravedad, "En revision", random ));
            colatotal.encolar(new Denuncia((String) cmbCaracter.getSelectedItem(), (String) cmbInstancia.getSelectedItem(), (String) cmbAsistencia.getSelectedItem(), txtResponsables.getText(), txaCarta.getText(), usu.getCedula(), gravedad, "En revision", random ));
            usu.setColaden(colacpusu);
            /*dlm.removeAllElements();
            ArrayList<Denuncia> listado = colacpusu.obtenerTodos();

            Collections.sort(listado);
            for (Denuncia obj : listado) {
                dlm.addElement(obj.toString());
            }*/
            
            mn.usu = usu;
            mn.lt = lt;
            mn.denuncia = denuncia;
            mn.denuncias = denuncias;
            mn.colacpusu = colacpusu;
            mn.colatotal = colatotal;
            
            
            //txaDenuncias.setText(denuncias.mo);
//Listar();
            JOptionPane.showMessageDialog(null, "DENUNCIA REGISTRADA CORRECTAMENTE");

        } else {
            JOptionPane.showMessageDialog(null, "COMPLETE LOS CAMPOS");
        }
    }//GEN-LAST:event_btnIngresarMouseClicked

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
        setColor(btnIngresar);
    }//GEN-LAST:event_btnIngresarMouseEntered

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
        resetColor(btnIngresar);
    }//GEN-LAST:event_btnIngresarMouseExited

    private void btnIngresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMousePressed

    }//GEN-LAST:event_btnIngresarMousePressed

    private void cmbCaracterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCaracterActionPerformed
        // TODO add your handling code here:
        cmbInstancia.setEnabled(true);
    }//GEN-LAST:event_cmbCaracterActionPerformed

    private void cmbInstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInstanciaActionPerformed
        // TODO add your handling code here:
        cmbAsistencia.setEnabled(true);
    }//GEN-LAST:event_cmbInstanciaActionPerformed

    private void cmbAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAsistenciaActionPerformed
        // TODO add your handling code here:
        txtResponsables.setEnabled(true);
        txaCarta.setEnabled(true);
    }//GEN-LAST:event_cmbAsistenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel btnIngresar;
    private javax.swing.JComboBox<String> cmbAsistencia;
    private javax.swing.JComboBox<String> cmbCaracter;
    private javax.swing.JComboBox<String> cmbInstancia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaCarta;
    private javax.swing.JTextField txtResponsables;
    // End of variables declaration//GEN-END:variables
}
