/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Clases.Arbol;
import Clases.ColaConPrioridad;
import Clases.Denuncia;
import Clases.Lista;
import Clases.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author rosco
 */
public class Login extends javax.swing.JFrame {

    Usuario usu = new Usuario();
    Lista lt = new Lista();
    Denuncia denuncia = new Denuncia();
    Arbol denuncias = new Arbol();
    ColaConPrioridad colacpusu = new ColaConPrioridad();
    ColaConPrioridad colatotal = new ColaConPrioridad();
    ColaConPrioridad colaabg = new ColaConPrioridad();
    int xMouse, yMouse;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public boolean verificarVacio(String texto) {
        return texto.isEmpty();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        citibg = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        tituloLogo = new javax.swing.JLabel();
        tituloIniciarSesion = new javax.swing.JLabel();
        tituloUsuario = new javax.swing.JLabel();
        campoCorreo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        tituloContrasenia = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        campoClave = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JPanel();
        txtEntrar = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JPanel();
        txtRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura-removebg-preview (1).png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 250, 10));

        jLabel15.setFont(new java.awt.Font("Roboto Black", 1, 60)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 0));
        jLabel15.setText("CI");
        background.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, 50));

        jLabel14.setFont(new java.awt.Font("Roboto Medium", 1, 23)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DERECHOS HUMANOS");
        background.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, 30));

        jLabel17.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 0));
        jLabel17.setText("Comité Comisionado Internacional");
        background.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 250, 20));

        jLabel16.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DHU");
        background.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 130, 50));
        background.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 250, 10));

        citibg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/city.png"))); // NOI18N
        background.add(citibg, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 280, 500));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
        });

        txtSalir.setBackground(new java.awt.Color(255, 255, 255));
        txtSalir.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("X");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 783, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 40));

        tituloLogo.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        tituloLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/favicon.png"))); // NOI18N
        tituloLogo.setText("SRECJ");
        background.add(tituloLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        tituloIniciarSesion.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        tituloIniciarSesion.setText("INICIAR SESION");
        background.add(tituloIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        tituloUsuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        tituloUsuario.setText("USUARIO");
        background.add(tituloUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        campoCorreo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoCorreo.setForeground(new java.awt.Color(204, 204, 204));
        campoCorreo.setText("Ingrese su correo electronico");
        campoCorreo.setBorder(null);
        campoCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoCorreoMousePressed(evt);
            }
        });
        background.add(campoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 450, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 153, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 450, 10));

        tituloContrasenia.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        tituloContrasenia.setText("CONTRASEÑA");
        background.add(tituloContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 153, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 450, 10));

        campoClave.setForeground(new java.awt.Color(204, 204, 204));
        campoClave.setText("********");
        campoClave.setBorder(null);
        campoClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoClaveMousePressed(evt);
            }
        });
        background.add(campoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 450, 40));

        btnEntrar.setBackground(new java.awt.Color(0, 134, 190));

        txtEntrar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtEntrar.setForeground(new java.awt.Color(255, 255, 255));
        txtEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEntrar.setText("ENTRAR");
        txtEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEntrarLayout = new javax.swing.GroupLayout(btnEntrar);
        btnEntrar.setLayout(btnEntrarLayout);
        btnEntrarLayout.setHorizontalGroup(
            btnEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnEntrarLayout.setVerticalGroup(
            btnEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 160, 50));

        btnRegistrarse.setBackground(new java.awt.Color(0, 134, 190));

        txtRegistro.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtRegistro.setForeground(new java.awt.Color(255, 255, 255));
        txtRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRegistro.setText("REGISTRARSE");
        txtRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtRegistroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRegistrarseLayout = new javax.swing.GroupLayout(btnRegistrarse);
        btnRegistrarse.setLayout(btnRegistrarseLayout);
        btnRegistrarseLayout.setHorizontalGroup(
            btnRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        btnRegistrarseLayout.setVerticalGroup(
            btnRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        background.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        // TODO add your handling code here: 
        System.exit(0);
    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(Color.red);
        txtSalir.setForeground(Color.white);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(Color.white);
        txtSalir.setForeground(Color.black);
    }//GEN-LAST:event_txtSalirMouseExited

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked

    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitMouseExited

    private void txtEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntrarMouseEntered
        // TODO add your handling code here:
        btnEntrar.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_txtEntrarMouseEntered

    private void txtRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegistroMouseEntered
        // TODO add your handling code here:
        btnRegistrarse.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_txtRegistroMouseEntered

    private void txtEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntrarMouseExited
        // TODO add your handling code here:
        btnEntrar.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_txtEntrarMouseExited

    private void txtRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegistroMouseExited
        // TODO add your handling code here:
        btnRegistrarse.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_txtRegistroMouseExited

    private void campoCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCorreoMousePressed
        // TODO add your handling code here:
        if (campoCorreo.getText().equals("Ingrese su correo electronico")) {
            campoCorreo.setText("");
            campoCorreo.setForeground(Color.black);
        }
        if (String.valueOf(campoClave.getPassword()).isEmpty()) {
            campoClave.setText("********");
            campoClave.setForeground(Color.gray);
        }
    }//GEN-LAST:event_campoCorreoMousePressed

    private void campoClaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoClaveMousePressed
        // TODO add your handling code here:
        if (String.valueOf(campoClave.getPassword()).equals("********")) {
            campoClave.setText("");
            campoClave.setForeground(Color.black);
        }
        if (campoCorreo.getText().isEmpty()) {
            campoCorreo.setText("Ingrese su correo electronico");
            campoCorreo.setForeground(Color.gray);
        }

    }//GEN-LAST:event_campoClaveMousePressed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void txtRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegistroMouseClicked
        // TODO add your handling code here:
        Registro rg = new Registro();
        rg.usu = usu;
        rg.lt = lt;
        rg.denuncia = denuncia;
        rg.denuncias = denuncias;
        rg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtRegistroMouseClicked

    private void txtEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntrarMouseClicked
        // TODO add your handling code here:
        MenuUsuario mn = new MenuUsuario();
        MenuAbogado ma = new MenuAbogado();
        MenuPresidente mp = new MenuPresidente();
        Usuario aux = lt.login(campoCorreo.getText(), campoClave.getText());
        String tipoUsuario = aux.getTipo();
        if (!verificarVacio(campoCorreo.getText()) && !verificarVacio(campoClave.getText()) ||( !lt.buscarCorreo(campoCorreo.getText())  && !lt.buscarClave(campoClave.getText()))) {
            switch (tipoUsuario) {
                case "Abogado":
                    ma.usu = aux;
                    ma.lt = lt;
                    ma.denuncia = denuncia;
                    ma.denuncias = denuncias;
                    ma.colacpusu = colacpusu;
                    ma.colatotal = colatotal;
                    ma.setVisible(true);
                    this.dispose();
                    break;
                case "Comun":
                    mn.usu = aux;
                    mn.lt = lt;
                    mn.denuncia = denuncia;
                    mn.denuncias = denuncias;
                    mn.colacpusu = colacpusu;
                    mn.colatotal = colatotal;
                    mn.setVisible(true);
                    this.dispose();
                    break;
                case "Presidente":
                    mp.usu = aux;
                    mp.lt = lt;
                    mp.denuncia = denuncia;
                    mp.denuncias = denuncias;
                    mp.colacpusu = colacpusu;
                    
                    mp.colatotal = colatotal;
                    mp.setVisible(true);
                    this.dispose();
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "DATOS INCORRECTOS");
                    break;
            }
            
        } else
            JOptionPane.showMessageDialog(null, "DATOS INCORRECTOS");
    }//GEN-LAST:event_txtEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnEntrar;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnRegistrarse;
    private javax.swing.JPasswordField campoClave;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JLabel citibg;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel tituloContrasenia;
    private javax.swing.JLabel tituloIniciarSesion;
    private javax.swing.JLabel tituloLogo;
    private javax.swing.JLabel tituloUsuario;
    private javax.swing.JLabel txtEntrar;
    private javax.swing.JLabel txtRegistro;
    private javax.swing.JLabel txtSalir;
    // End of variables declaration//GEN-END:variables
}
