/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Clases.Arbol;
import Clases.ColaConPrioridad;
import Clases.Denuncia;
import Clases.Lista;
import Clases.Usuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;

/**
 *
 * @author rosco
 */
public class MenuAbogado extends javax.swing.JFrame {
    int xMouse, yMouse;
    Usuario usu = new Usuario();
    Lista lt = new Lista();
    Denuncia denuncia = new Denuncia();
    Arbol denuncias = new Arbol();
    DefaultListModel dlm = new DefaultListModel();
    ColaConPrioridad colacpusu = new ColaConPrioridad();
    ColaConPrioridad colatotal = new ColaConPrioridad();  
    ColaConPrioridad colaabg = new ColaConPrioridad();
    /**
     * Creates new form Registro
     */
    public MenuAbogado() {
        initComponents();
        
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," ;Septiembre"
            ,"Octubre","Noviembre","Diciemrbre"};
        fecha.setText("Hoy es "+dia+" de "+meses[month - 1]+" de "+year);
        
        PrincipalAbogado p1 = new PrincipalAbogado();
        p1.setSize(750, 460);
        p1.setLocation(0,0);
        
        Contenido.removeAll();
        Contenido.add(p1, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnPrincipal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCasosAsignados = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnCerrarCaso = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bntDisponibilidad = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnCitaGerencia = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnPapeleraCasos = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        ubicacion = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        Tittle = new javax.swing.JPanel();
        CuadroCerrado = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        Slogan = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(13, 71, 161));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SRECJ");
        Menu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));
        Menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, 20));

        btnPrincipal.setBackground(new java.awt.Color(21, 101, 192));
        btnPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrincipalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrincipalMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Principal");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home-outline.png"))); // NOI18N

        javax.swing.GroupLayout btnPrincipalLayout = new javax.swing.GroupLayout(btnPrincipal);
        btnPrincipal.setLayout(btnPrincipalLayout);
        btnPrincipalLayout.setHorizontalGroup(
            btnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPrincipalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        btnPrincipalLayout.setVerticalGroup(
            btnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPrincipalLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(btnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Menu.add(btnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 50));

        btnCasosAsignados.setBackground(new java.awt.Color(18, 90, 173));
        btnCasosAsignados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCasosAsignadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCasosAsignadosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCasosAsignadosMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Casos Asignados");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_download_24px.png"))); // NOI18N

        javax.swing.GroupLayout btnCasosAsignadosLayout = new javax.swing.GroupLayout(btnCasosAsignados);
        btnCasosAsignados.setLayout(btnCasosAsignadosLayout);
        btnCasosAsignadosLayout.setHorizontalGroup(
            btnCasosAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCasosAsignadosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        btnCasosAsignadosLayout.setVerticalGroup(
            btnCasosAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCasosAsignadosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(btnCasosAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Menu.add(btnCasosAsignados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 270, 50));

        btnCerrarCaso.setBackground(new java.awt.Color(18, 90, 173));
        btnCerrarCaso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarCasoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarCasoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarCasoMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cerrar Caso");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_pane_24px.png"))); // NOI18N

        javax.swing.GroupLayout btnCerrarCasoLayout = new javax.swing.GroupLayout(btnCerrarCaso);
        btnCerrarCaso.setLayout(btnCerrarCasoLayout);
        btnCerrarCasoLayout.setHorizontalGroup(
            btnCerrarCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCerrarCasoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        btnCerrarCasoLayout.setVerticalGroup(
            btnCerrarCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCerrarCasoLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(btnCerrarCasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7))
                .addGap(22, 22, 22))
        );

        Menu.add(btnCerrarCaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, -1));

        bntDisponibilidad.setBackground(new java.awt.Color(18, 90, 173));
        bntDisponibilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntDisponibilidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntDisponibilidadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bntDisponibilidadMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cambiar Disponibilidad");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_available_updates_24px.png"))); // NOI18N

        javax.swing.GroupLayout bntDisponibilidadLayout = new javax.swing.GroupLayout(bntDisponibilidad);
        bntDisponibilidad.setLayout(bntDisponibilidadLayout);
        bntDisponibilidadLayout.setHorizontalGroup(
            bntDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bntDisponibilidadLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        bntDisponibilidadLayout.setVerticalGroup(
            bntDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bntDisponibilidadLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(bntDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8))
                .addGap(15, 15, 15))
        );

        Menu.add(bntDisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 270, 50));

        btnCitaGerencia.setBackground(new java.awt.Color(18, 90, 173));
        btnCitaGerencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCitaGerenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCitaGerenciaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCitaGerenciaMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cita Gerencia");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Date_To_24px.png"))); // NOI18N

        javax.swing.GroupLayout btnCitaGerenciaLayout = new javax.swing.GroupLayout(btnCitaGerencia);
        btnCitaGerencia.setLayout(btnCitaGerenciaLayout);
        btnCitaGerenciaLayout.setHorizontalGroup(
            btnCitaGerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCitaGerenciaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        btnCitaGerenciaLayout.setVerticalGroup(
            btnCitaGerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCitaGerenciaLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(btnCitaGerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9))
                .addGap(15, 15, 15))
        );

        Menu.add(btnCitaGerencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 270, 50));
        Menu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 250, 10));

        jLabel15.setFont(new java.awt.Font("Roboto Black", 1, 60)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 0));
        jLabel15.setText("CI");
        Menu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, 50));

        jLabel16.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DHU");
        Menu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 130, 50));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        Menu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 250, 10));

        jLabel17.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 0));
        jLabel17.setText("Comité Comisionado Internacional");
        Menu.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 250, -1));

        jLabel14.setFont(new java.awt.Font("Roboto Medium", 1, 23)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DERECHOS HUMANOS");
        Menu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        btnPapeleraCasos.setBackground(new java.awt.Color(18, 90, 173));
        btnPapeleraCasos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPapeleraCasosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPapeleraCasosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPapeleraCasosMousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Papelera de Casos");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_waste_24px.png"))); // NOI18N

        javax.swing.GroupLayout btnPapeleraCasosLayout = new javax.swing.GroupLayout(btnPapeleraCasos);
        btnPapeleraCasos.setLayout(btnPapeleraCasosLayout);
        btnPapeleraCasosLayout.setHorizontalGroup(
            btnPapeleraCasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPapeleraCasosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        btnPapeleraCasosLayout.setVerticalGroup(
            btnPapeleraCasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPapeleraCasosLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(btnPapeleraCasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addGap(15, 15, 15))
        );

        Menu.add(btnPapeleraCasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 270, 50));

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 640));

        Header.setBackground(new java.awt.Color(25, 118, 210));

        ubicacion.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ubicacion.setForeground(new java.awt.Color(255, 255, 255));
        ubicacion.setText("Abogado/Menu/Principal");

        fecha.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("Hoy es Sábado 28 de Abril de 2022");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha)
                    .addComponent(ubicacion))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ubicacion)
                .addGap(27, 27, 27)
                .addComponent(fecha)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        Background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 750, 120));

        Tittle.setBackground(new java.awt.Color(255, 255, 255));
        Tittle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TittleMouseDragged(evt);
            }
        });
        Tittle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TittleMousePressed(evt);
            }
        });

        CuadroCerrado.setBackground(new java.awt.Color(255, 255, 255));

        txtCerrar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CuadroCerradoLayout = new javax.swing.GroupLayout(CuadroCerrado);
        CuadroCerrado.setLayout(CuadroCerradoLayout);
        CuadroCerradoLayout.setHorizontalGroup(
            CuadroCerradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );
        CuadroCerradoLayout.setVerticalGroup(
            CuadroCerradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TittleLayout = new javax.swing.GroupLayout(Tittle);
        Tittle.setLayout(TittleLayout);
        TittleLayout.setHorizontalGroup(
            TittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TittleLayout.createSequentialGroup()
                .addGap(0, 991, Short.MAX_VALUE)
                .addComponent(CuadroCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TittleLayout.setVerticalGroup(
            TittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TittleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CuadroCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Background.add(Tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 30));

        Slogan.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        Slogan.setText("Comprometidos con los derechos humanos y la sociedad!");
        Background.add(Slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        Contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        Background.add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 750, 460));

        btnLogOut.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Logout_Rounded_Left_24px_1.png"))); // NOI18N
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        Background.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TittleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TittleMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_TittleMousePressed

    private void TittleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TittleMouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_TittleMouseDragged

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        // TODO add your handling code here:
        CuadroCerrado.setBackground(Color.red);
        txtCerrar.setForeground(Color.white);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        // TODO add your handling code here:
        CuadroCerrado.setBackground(Color.white);
        txtCerrar.setForeground(Color.black);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void btnPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMouseEntered
        // TODO add your handling code here:
            if(btnPrincipal.getBackground().getRGB() == -15574355)
            setColor(btnPrincipal);

    }//GEN-LAST:event_btnPrincipalMouseEntered

    private void btnPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMousePressed
        // TODO add your handling code here:
        setColor(btnPrincipal);
        resetColor(btnCasosAsignados);
        resetColor(btnCerrarCaso);
        resetColor(bntDisponibilidad);
        resetColor(btnCitaGerencia);
        resetColor(btnPapeleraCasos);
        ubicacion.setText("Abogado/Menu/Principal");
        PrincipalAbogado p1 = new PrincipalAbogado();
        p1.setSize(750, 460);
        p1.setLocation(0,0);

        
        Contenido.removeAll();
        Contenido.add(p1, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_btnPrincipalMousePressed

    private void btnPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMouseExited
        // TODO add your handling code here:
            if(btnCasosAsignados.getBackground().getRGB() != -15574355 || bntDisponibilidad.getBackground().getRGB() != -15574355
            || btnCerrarCaso.getBackground().getRGB() != -15574355 || btnCitaGerencia.getBackground().getRGB() != -15574355 || btnPapeleraCasos.getBackground().getRGB() != -15574355)
            resetColor(btnPrincipal);
    }//GEN-LAST:event_btnPrincipalMouseExited

    private void btnCasosAsignadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasosAsignadosMousePressed
        // TODO add your handling code here:
        
        cambiarDisponibilidad camDisp = new cambiarDisponibilidad();
        LitigarCaso lc = new LitigarCaso();
        mostrarDenunciasAbogado mda = new mostrarDenunciasAbogado();
        CitaGerencia cg = new CitaGerencia();
        resetColor(btnPrincipal);
        setColor(btnCasosAsignados);
        resetColor(btnCerrarCaso);
        resetColor(bntDisponibilidad);
        resetColor(btnCitaGerencia);
        resetColor(btnPapeleraCasos);
        ubicacion.setText("Abogado/Menu/Casos Asignados");
        
        camDisp.usu = usu;
        camDisp.lt = lt;
        camDisp.denuncia = denuncia;
        camDisp.denuncias = denuncias;
        camDisp.colaabg = colaabg;
        camDisp.colacpusu = colacpusu;
        camDisp.colatotal = colatotal;
        
        lc.usu = usu;
        lc.lt = lt;
        lc.denuncia = denuncia;
        lc.denuncias = denuncias;
        lc.colaabg = colaabg;
        lc.colacpusu = colacpusu;
        lc.colatotal = colatotal;
        
        mda.usu = usu;
        mda.lt = lt;
        mda.denuncia = denuncia;
        mda.denuncias = denuncias;
        mda.colaabg = colaabg;
        mda.colacpusu = colacpusu;
        mda.colatotal = colatotal;
        
        cg.usu = usu;
        cg.lt = lt;
        cg.denuncia = denuncia;
        cg.denuncias = denuncias;
        cg.colaabg = colaabg;
        cg.colacpusu = colacpusu;
        cg.colatotal = colatotal;
        
        mda.setSize(750, 460);
        mda.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(mda, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
        
    }//GEN-LAST:event_btnCasosAsignadosMousePressed

    private void btnCasosAsignadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasosAsignadosMouseEntered
        // TODO add your handling code here:
        if(btnCasosAsignados.getBackground().getRGB() == -15574355)
            setColor(btnCasosAsignados);
    }//GEN-LAST:event_btnCasosAsignadosMouseEntered

    private void btnCasosAsignadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasosAsignadosMouseExited
        // TODO add your handling code here:
        if(btnPrincipal.getBackground().getRGB() != -15574355 || bntDisponibilidad.getBackground().getRGB() != -15574355
            || btnCerrarCaso.getBackground().getRGB() != -15574355 || btnCitaGerencia.getBackground().getRGB() != -15574355|| btnPapeleraCasos.getBackground().getRGB() != -15574355)
            resetColor(btnCasosAsignados);
    }//GEN-LAST:event_btnCasosAsignadosMouseExited

    private void btnCerrarCasoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarCasoMousePressed
        // TODO add your handling code here:
                cambiarDisponibilidad camDisp = new cambiarDisponibilidad();
        LitigarCaso lc = new LitigarCaso();
        mostrarDenunciasAbogado mda = new mostrarDenunciasAbogado();
        CitaGerencia cg = new CitaGerencia();
        resetColor(btnPrincipal);
        resetColor(btnCasosAsignados);
        setColor(btnCerrarCaso);
        resetColor(bntDisponibilidad);
        resetColor(btnCitaGerencia);
        resetColor(btnPapeleraCasos);
        ubicacion.setText("Abogado/Menu/Cerrar Casos");
        
        camDisp.usu = usu;
        camDisp.lt = lt;
        camDisp.denuncia = denuncia;
        camDisp.denuncias = denuncias;
        camDisp.colaabg = colaabg;
        camDisp.colacpusu = colacpusu;
        camDisp.colatotal = colatotal;
        
        lc.usu = usu;
        lc.lt = lt;
        lc.denuncia = denuncia;
        lc.denuncias = denuncias;
        lc.colaabg = colaabg;
        lc.colacpusu = colacpusu;
        lc.colatotal = colatotal;
        
        mda.usu = usu;
        mda.lt = lt;
        mda.denuncia = denuncia;
        mda.denuncias = denuncias;
        mda.colaabg = colaabg;
        mda.colacpusu = colacpusu;
        mda.colatotal = colatotal;
        
        cg.usu = usu;
        cg.lt = lt;
        cg.denuncia = denuncia;
        cg.denuncias = denuncias;
        cg.colaabg = colaabg;
        cg.colacpusu = colacpusu;
        cg.colatotal = colatotal;
        
        lc.setSize(750, 460);
        lc.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(lc, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_btnCerrarCasoMousePressed

    private void btnCerrarCasoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarCasoMouseEntered
        // TODO add your handling code here:
        if(btnCerrarCaso.getBackground().getRGB() == -15574355)
            setColor(btnCerrarCaso);
    }//GEN-LAST:event_btnCerrarCasoMouseEntered

    private void btnCerrarCasoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarCasoMouseExited
        // TODO add your handling code here:
        if(btnPrincipal.getBackground().getRGB() != -15574355 || bntDisponibilidad.getBackground().getRGB() != -15574355
            || btnCasosAsignados.getBackground().getRGB() != -15574355 || btnCitaGerencia.getBackground().getRGB() != -15574355|| btnPapeleraCasos.getBackground().getRGB() != -15574355)
            resetColor(btnCerrarCaso);
    }//GEN-LAST:event_btnCerrarCasoMouseExited

    private void bntDisponibilidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntDisponibilidadMousePressed
        // TODO add your handling code here:
        cambiarDisponibilidad camDisp = new cambiarDisponibilidad();
        LitigarCaso lc = new LitigarCaso();
        mostrarDenunciasAbogado mda = new mostrarDenunciasAbogado();
        CitaGerencia cg = new CitaGerencia();
        
        resetColor(btnPrincipal);
        resetColor(btnCasosAsignados);
        resetColor(btnCerrarCaso);
        setColor(bntDisponibilidad);
        resetColor(btnCitaGerencia);
        resetColor(btnPapeleraCasos);
        
        ubicacion.setText("Abogado/Menu/Cambiar Disponibilidad");
        
        camDisp.usu = usu;
        camDisp.lt = lt;
        camDisp.denuncia = denuncia;
        camDisp.denuncias = denuncias;
        camDisp.colaabg = colaabg;
        camDisp.colacpusu = colacpusu;
        camDisp.colatotal = colatotal;
        
        lc.usu = usu;
        lc.lt = lt;
        lc.denuncia = denuncia;
        lc.denuncias = denuncias;
        lc.colaabg = colaabg;
        lc.colacpusu = colacpusu;
        lc.colatotal = colatotal;
        
        mda.usu = usu;
        mda.lt = lt;
        mda.denuncia = denuncia;
        mda.denuncias = denuncias;
        mda.colaabg = colaabg;
        mda.colacpusu = colacpusu;
        mda.colatotal = colatotal;
        
        cg.usu = usu;
        cg.lt = lt;
        cg.denuncia = denuncia;
        cg.denuncias = denuncias;
        cg.colaabg = colaabg;
        cg.colacpusu = colacpusu;
        cg.colatotal = colatotal;
        
        camDisp.setSize(750, 460);
        camDisp.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(camDisp, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_bntDisponibilidadMousePressed

    private void bntDisponibilidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntDisponibilidadMouseEntered
        // TODO add your handling code here:
        if(bntDisponibilidad.getBackground().getRGB() == -15574355)
            setColor(bntDisponibilidad);
    }//GEN-LAST:event_bntDisponibilidadMouseEntered

    private void bntDisponibilidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntDisponibilidadMouseExited
        // TODO add your handling code here:
        if(btnPrincipal.getBackground().getRGB() != -15574355 || btnCerrarCaso.getBackground().getRGB() != -15574355
            || btnCasosAsignados.getBackground().getRGB() != -15574355 || btnCitaGerencia.getBackground().getRGB() != -15574355|| btnPapeleraCasos.getBackground().getRGB() != -15574355)
            resetColor(bntDisponibilidad);
    }//GEN-LAST:event_bntDisponibilidadMouseExited

    private void btnCitaGerenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCitaGerenciaMouseEntered
        // TODO add your handling code here:
        if(btnCitaGerencia.getBackground().getRGB() == -15574355)
            setColor(btnCitaGerencia);        
    }//GEN-LAST:event_btnCitaGerenciaMouseEntered

    private void btnCitaGerenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCitaGerenciaMouseExited
        // TODO add your handling code here:
        if(btnPrincipal.getBackground().getRGB() != -15574355 || btnCerrarCaso.getBackground().getRGB() != -15574355
            || btnCasosAsignados.getBackground().getRGB() != -15574355 || bntDisponibilidad.getBackground().getRGB() != -15574355|| btnPapeleraCasos.getBackground().getRGB() != -15574355)
            resetColor(btnCitaGerencia);
    }//GEN-LAST:event_btnCitaGerenciaMouseExited

    private void btnCitaGerenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCitaGerenciaMousePressed
        // TODO add your handling code here:
                cambiarDisponibilidad camDisp = new cambiarDisponibilidad();
        LitigarCaso lc = new LitigarCaso();
        mostrarDenunciasAbogado mda = new mostrarDenunciasAbogado();
        CitaGerencia cg = new CitaGerencia();
        resetColor(btnPrincipal);
        resetColor(btnCasosAsignados);
        resetColor(btnCerrarCaso);
        resetColor(bntDisponibilidad);
        setColor(btnCitaGerencia);
        resetColor(btnPapeleraCasos);
        ubicacion.setText("Abogado/Menu/Cita Gerencia");
        
        camDisp.usu = usu;
        camDisp.lt = lt;
        camDisp.denuncia = denuncia;
        camDisp.denuncias = denuncias;
        camDisp.colaabg = colaabg;
        camDisp.colacpusu = colacpusu;
        camDisp.colatotal = colatotal;
        
        lc.usu = usu;
        lc.lt = lt;
        lc.denuncia = denuncia;
        lc.denuncias = denuncias;
        lc.colaabg = colaabg;
        lc.colacpusu = colacpusu;
        lc.colatotal = colatotal;
        
        mda.usu = usu;
        mda.lt = lt;
        mda.denuncia = denuncia;
        mda.denuncias = denuncias;
        mda.colaabg = colaabg;
        mda.colacpusu = colacpusu;
        mda.colatotal = colatotal;
        
        cg.usu = usu;
        cg.lt = lt;
        cg.denuncia = denuncia;
        cg.denuncias = denuncias;
        cg.colaabg = colaabg;
        cg.colacpusu = colacpusu;
        cg.colatotal = colatotal;
        
        cg.setSize(750, 460);
        cg.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(cg, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_btnCitaGerenciaMousePressed

    private void btnPapeleraCasosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPapeleraCasosMouseEntered
        // TODO add your handling code here:
        if(btnPapeleraCasos.getBackground().getRGB() == -15574355)
            setColor(btnPapeleraCasos);         
    }//GEN-LAST:event_btnPapeleraCasosMouseEntered

    private void btnPapeleraCasosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPapeleraCasosMouseExited
        // TODO add your handling code here:
       if(btnPrincipal.getBackground().getRGB() != -15574355 || btnCerrarCaso.getBackground().getRGB() != -15574355
            || btnCasosAsignados.getBackground().getRGB() != -15574355 || bntDisponibilidad.getBackground().getRGB() != -15574355|| btnCitaGerencia.getBackground().getRGB() != -15574355)
            resetColor(btnPapeleraCasos);
    }//GEN-LAST:event_btnPapeleraCasosMouseExited

    private void btnPapeleraCasosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPapeleraCasosMousePressed
        // TODO add your handling code here:
        resetColor(btnPrincipal);
        resetColor(btnCasosAsignados);
        resetColor(btnCerrarCaso);
        resetColor(bntDisponibilidad);
        resetColor(btnCitaGerencia);
        setColor(btnPapeleraCasos);
        ubicacion.setText("Abogado/Menu/Papelera De Casos");        
    }//GEN-LAST:event_btnPapeleraCasosMousePressed

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        // TODO add your handling code here:
        Login lg=new Login();
        lg.usu=null;
        lg.lt=lt;
        lg.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnLogOutMouseClicked

    /**
     * @param args the command line arguments
     */
        void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAbogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAbogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAbogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAbogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAbogado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel CuadroCerrado;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Slogan;
    private javax.swing.JPanel Tittle;
    private javax.swing.JPanel bntDisponibilidad;
    private javax.swing.JPanel btnCasosAsignados;
    private javax.swing.JPanel btnCerrarCaso;
    private javax.swing.JPanel btnCitaGerencia;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JPanel btnPapeleraCasos;
    private javax.swing.JPanel btnPrincipal;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel txtCerrar;
    private javax.swing.JLabel ubicacion;
    // End of variables declaration//GEN-END:variables
}
