/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Clases.Arbol;
import Clases.ColaConPrioridad;
import Clases.Denuncia;
import Clases.Lista;
import Clases.Usuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JPanel;

/**
 *
 * @author rosco
 */
public class MenuUsuario extends javax.swing.JFrame {

    int xMouse, yMouse;
    Usuario usu = new Usuario();
    Lista lt = new Lista();
    Denuncia denuncia = new Denuncia();
    Arbol denuncias = new Arbol();
    ColaConPrioridad colacpusu = new ColaConPrioridad();
    ColaConPrioridad colatotal = new ColaConPrioridad();

    /**
     * Creates new form Registro
     */
    public MenuUsuario() {
        initComponents();

        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", " ;Septiembre",
            "Octubre", "Noviembre", "Diciemrbre"};
        fecha.setText("Hoy es " + dia + " de " + meses[month - 1] + " de " + year);

        Principal p1 = new Principal();
        p1.setSize(750, 460);
        p1.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(p1, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnPrincipal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCrearDenuncia = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnVerCasos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnModificarDenuncias = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnEliminarDenuncia = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        ubicacion = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        Tittle = new javax.swing.JPanel();
        CuadroCerrado = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        Slogan = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(13, 71, 161));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SRECJ");
        Menu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));
        Menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, 20));

        btnPrincipal.setBackground(new java.awt.Color(21, 101, 192));
        btnPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrincipalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrincipalMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Principal");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home-outline.png"))); // NOI18N

        javax.swing.GroupLayout btnPrincipalLayout = new javax.swing.GroupLayout(btnPrincipal);
        btnPrincipal.setLayout(btnPrincipalLayout);
        btnPrincipalLayout.setHorizontalGroup(
            btnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPrincipalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        btnPrincipalLayout.setVerticalGroup(
            btnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPrincipalLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(btnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Menu.add(btnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 50));

        btnCrearDenuncia.setBackground(new java.awt.Color(18, 90, 173));
        btnCrearDenuncia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearDenunciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearDenunciaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCrearDenunciaMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Crear Denuncia");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_plus_+_24px.png"))); // NOI18N

        javax.swing.GroupLayout btnCrearDenunciaLayout = new javax.swing.GroupLayout(btnCrearDenuncia);
        btnCrearDenuncia.setLayout(btnCrearDenunciaLayout);
        btnCrearDenunciaLayout.setHorizontalGroup(
            btnCrearDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCrearDenunciaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        btnCrearDenunciaLayout.setVerticalGroup(
            btnCrearDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCrearDenunciaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(btnCrearDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Menu.add(btnCrearDenuncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 270, 50));

        btnVerCasos.setBackground(new java.awt.Color(18, 90, 173));
        btnVerCasos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerCasosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerCasosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVerCasosMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ver Denuncias");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_24px.png"))); // NOI18N

        javax.swing.GroupLayout btnVerCasosLayout = new javax.swing.GroupLayout(btnVerCasos);
        btnVerCasos.setLayout(btnVerCasosLayout);
        btnVerCasosLayout.setHorizontalGroup(
            btnVerCasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVerCasosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        btnVerCasosLayout.setVerticalGroup(
            btnVerCasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVerCasosLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(btnVerCasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7))
                .addGap(22, 22, 22))
        );

        Menu.add(btnVerCasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, -1));

        btnModificarDenuncias.setBackground(new java.awt.Color(18, 90, 173));
        btnModificarDenuncias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarDenunciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarDenunciasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModificarDenunciasMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Modificar Denuncia");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_edit_file_24px.png"))); // NOI18N

        javax.swing.GroupLayout btnModificarDenunciasLayout = new javax.swing.GroupLayout(btnModificarDenuncias);
        btnModificarDenuncias.setLayout(btnModificarDenunciasLayout);
        btnModificarDenunciasLayout.setHorizontalGroup(
            btnModificarDenunciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModificarDenunciasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        btnModificarDenunciasLayout.setVerticalGroup(
            btnModificarDenunciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModificarDenunciasLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(btnModificarDenunciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8))
                .addGap(15, 15, 15))
        );

        Menu.add(btnModificarDenuncias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 270, 50));

        btnEliminarDenuncia.setBackground(new java.awt.Color(18, 90, 173));
        btnEliminarDenuncia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarDenunciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarDenunciaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarDenunciaMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Eliminar Denuncia");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Delete_File_24px.png"))); // NOI18N

        javax.swing.GroupLayout btnEliminarDenunciaLayout = new javax.swing.GroupLayout(btnEliminarDenuncia);
        btnEliminarDenuncia.setLayout(btnEliminarDenunciaLayout);
        btnEliminarDenunciaLayout.setHorizontalGroup(
            btnEliminarDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarDenunciaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        btnEliminarDenunciaLayout.setVerticalGroup(
            btnEliminarDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarDenunciaLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(btnEliminarDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9))
                .addGap(15, 15, 15))
        );

        Menu.add(btnEliminarDenuncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 270, 50));
        Menu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 250, 10));

        jLabel15.setFont(new java.awt.Font("Roboto Black", 1, 60)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 0));
        jLabel15.setText("CI");
        Menu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, 50));

        jLabel16.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DHU");
        Menu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 130, 50));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        Menu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 250, 10));

        jLabel17.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 0));
        jLabel17.setText("Comité Comisionado Internacional");
        Menu.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 250, -1));

        jLabel14.setFont(new java.awt.Font("Roboto Medium", 1, 23)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DERECHOS HUMANOS");
        Menu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 640));

        Header.setBackground(new java.awt.Color(25, 118, 210));

        ubicacion.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ubicacion.setForeground(new java.awt.Color(255, 255, 255));
        ubicacion.setText("Usuario/Menu/Principal");

        fecha.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("Hoy es Sábado 28 de Abril de 2022");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ubicacion)
                    .addComponent(fecha))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ubicacion)
                .addGap(26, 26, 26)
                .addComponent(fecha)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        Background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 750, 120));

        Tittle.setBackground(new java.awt.Color(255, 255, 255));
        Tittle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TittleMouseDragged(evt);
            }
        });
        Tittle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TittleMousePressed(evt);
            }
        });

        CuadroCerrado.setBackground(new java.awt.Color(255, 255, 255));

        txtCerrar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CuadroCerradoLayout = new javax.swing.GroupLayout(CuadroCerrado);
        CuadroCerrado.setLayout(CuadroCerradoLayout);
        CuadroCerradoLayout.setHorizontalGroup(
            CuadroCerradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );
        CuadroCerradoLayout.setVerticalGroup(
            CuadroCerradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TittleLayout = new javax.swing.GroupLayout(Tittle);
        Tittle.setLayout(TittleLayout);
        TittleLayout.setHorizontalGroup(
            TittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TittleLayout.createSequentialGroup()
                .addGap(0, 991, Short.MAX_VALUE)
                .addComponent(CuadroCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TittleLayout.setVerticalGroup(
            TittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TittleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CuadroCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Background.add(Tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 30));

        Slogan.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        Slogan.setText("Comprometidos con los derechos humanos y la sociedad!");
        Background.add(Slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        Contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        Background.add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 750, 460));

        btnLogOut.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Logout_Rounded_Left_24px_1.png"))); // NOI18N
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        Background.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TittleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TittleMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_TittleMousePressed

    private void TittleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TittleMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_TittleMouseDragged

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        // TODO add your handling code here:
        CuadroCerrado.setBackground(Color.red);
        txtCerrar.setForeground(Color.white);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        // TODO add your handling code here:
        CuadroCerrado.setBackground(Color.white);
        txtCerrar.setForeground(Color.black);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void btnPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMouseEntered
        // TODO add your handling code here:
        if (btnPrincipal.getBackground().getRGB() == -15574355) {
            setColor(btnPrincipal);
        }

    }//GEN-LAST:event_btnPrincipalMouseEntered

    private void btnPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMousePressed
        // TODO add your handling code here:
        DenunciaUsuario dusu = new DenunciaUsuario();
        MostrarDenunciasUsuario mdu = new MostrarDenunciasUsuario();
        ModificarDenuncia modDen = new ModificarDenuncia();
        setColor(btnPrincipal);
        resetColor(btnCrearDenuncia);
        resetColor(btnVerCasos);
        resetColor(btnModificarDenuncias);
        resetColor(btnEliminarDenuncia);
        ubicacion.setText("Usuario/Menu/Principal");
        Principal p1 = new Principal();
        p1.setSize(750, 460);
        p1.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(p1, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
        mdu.usu = usu;
        mdu.lt = lt;
        mdu.denuncia = denuncia;
        mdu.denuncias = denuncias;
        mdu.colacpusu = colacpusu;
        mdu.colatotal = colatotal;

        dusu.usu = usu;
        dusu.lt = lt;
        dusu.denuncia = denuncia;
        dusu.denuncias = denuncias;
        dusu.colacpusu = colacpusu;
        dusu.colatotal = colatotal;

        modDen.usu = usu;
        modDen.lt = lt;
        modDen.denuncia = denuncia;
        modDen.denuncias = denuncias;
        modDen.colacpusu = colacpusu;
        modDen.colatotal = colatotal;


    }//GEN-LAST:event_btnPrincipalMousePressed

    private void btnPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMouseExited
        // TODO add your handling code here:
        if (btnCrearDenuncia.getBackground().getRGB() != -15574355 || btnModificarDenuncias.getBackground().getRGB() != -15574355
                || btnVerCasos.getBackground().getRGB() != -15574355 || btnEliminarDenuncia.getBackground().getRGB() != -15574355)
            resetColor(btnPrincipal);
    }//GEN-LAST:event_btnPrincipalMouseExited

    private void btnCrearDenunciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearDenunciaMousePressed
        // TODO add your handling code here:
        MostrarDenunciasUsuario mdu = new MostrarDenunciasUsuario();
        DenunciaUsuario dusu = new DenunciaUsuario();
        ModificarDenuncia modDen = new ModificarDenuncia();

        resetColor(btnPrincipal);
        setColor(btnCrearDenuncia);
        resetColor(btnVerCasos);
        resetColor(btnModificarDenuncias);
        resetColor(btnEliminarDenuncia);
        ubicacion.setText("Usuario/Menu/Crear Denuncia");

        dusu.setSize(750, 460);
        dusu.setLocation(0, 0);
        mdu.usu = usu;
        mdu.lt = lt;
        mdu.denuncia = denuncia;
        mdu.denuncias = denuncias;
        mdu.colacpusu = colacpusu;
        mdu.colatotal = colatotal;

        dusu.usu = usu;
        dusu.lt = lt;
        dusu.denuncia = denuncia;
        dusu.denuncias = denuncias;
        dusu.colacpusu = colacpusu;
        dusu.colatotal = colatotal;

        modDen.usu = usu;
        modDen.lt = lt;
        modDen.denuncia = denuncia;
        modDen.denuncias = denuncias;
        modDen.colacpusu = colacpusu;
        modDen.colatotal = colatotal;

        Contenido.removeAll();
        Contenido.add(dusu, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();


    }//GEN-LAST:event_btnCrearDenunciaMousePressed

    private void btnCrearDenunciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearDenunciaMouseEntered
        // TODO add your handling code here:
        if (btnCrearDenuncia.getBackground().getRGB() == -15574355)
            setColor(btnCrearDenuncia);
    }//GEN-LAST:event_btnCrearDenunciaMouseEntered

    private void btnCrearDenunciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearDenunciaMouseExited
        // TODO add your handling code here:
        if (btnPrincipal.getBackground().getRGB() != -15574355 || btnModificarDenuncias.getBackground().getRGB() != -15574355
                || btnVerCasos.getBackground().getRGB() != -15574355 || btnEliminarDenuncia.getBackground().getRGB() != -15574355)
            resetColor(btnCrearDenuncia);
    }//GEN-LAST:event_btnCrearDenunciaMouseExited

    private void btnVerCasosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerCasosMousePressed
        // TODO add your handling code here:
        DenunciaUsuario dusu = new DenunciaUsuario();
        MostrarDenunciasUsuario mdu = new MostrarDenunciasUsuario();
        ModificarDenuncia modDen = new ModificarDenuncia();
        resetColor(btnPrincipal);
        resetColor(btnCrearDenuncia);
        setColor(btnVerCasos);
        resetColor(btnModificarDenuncias);
        resetColor(btnEliminarDenuncia);
        ubicacion.setText("Usuario/Menu/Ver Denuncias");

        mdu.setSize(750, 460);
        mdu.setLocation(0, 0);

        mdu.usu = usu;
        mdu.lt = lt;
        mdu.denuncia = denuncia;
        mdu.denuncias = denuncias;
        mdu.colacpusu = colacpusu;
        mdu.colatotal = colatotal;

        dusu.usu = usu;
        dusu.lt = lt;
        dusu.denuncia = denuncia;
        dusu.denuncias = denuncias;
        dusu.colacpusu = colacpusu;
        dusu.colatotal = colatotal;

        modDen.usu = usu;
        modDen.lt = lt;
        modDen.denuncia = denuncia;
        modDen.denuncias = denuncias;
        modDen.colacpusu = colacpusu;
        modDen.colatotal = colatotal;

        Contenido.removeAll();
        Contenido.add(mdu, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();


    }//GEN-LAST:event_btnVerCasosMousePressed

    private void btnVerCasosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerCasosMouseEntered
        // TODO add your handling code here:
        if (btnVerCasos.getBackground().getRGB() == -15574355)
            setColor(btnVerCasos);
    }//GEN-LAST:event_btnVerCasosMouseEntered

    private void btnVerCasosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerCasosMouseExited
        // TODO add your handling code here:
        if (btnPrincipal.getBackground().getRGB() != -15574355 || btnModificarDenuncias.getBackground().getRGB() != -15574355
                || btnCrearDenuncia.getBackground().getRGB() != -15574355 || btnEliminarDenuncia.getBackground().getRGB() != -15574355)
            resetColor(btnVerCasos);
    }//GEN-LAST:event_btnVerCasosMouseExited

    private void btnModificarDenunciasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarDenunciasMousePressed
        // TODO add your handling code here:
        DenunciaUsuario dusu = new DenunciaUsuario();
        MostrarDenunciasUsuario mdu = new MostrarDenunciasUsuario();
        ModificarDenuncia modDen = new ModificarDenuncia();
        EliminarDenunciaUsuario elimDen = new EliminarDenunciaUsuario();

        resetColor(btnPrincipal);
        resetColor(btnCrearDenuncia);
        resetColor(btnVerCasos);
        setColor(btnModificarDenuncias);
        resetColor(btnEliminarDenuncia);
        ubicacion.setText("Usuario/Menu/Modificar Denuncia");

        modDen.setSize(750, 460);
        modDen.setLocation(0, 0);

        mdu.usu = usu;
        mdu.lt = lt;
        mdu.denuncia = denuncia;
        mdu.denuncias = denuncias;
        mdu.colacpusu = colacpusu;
        mdu.colatotal = colatotal;

        dusu.usu = usu;
        dusu.lt = lt;
        dusu.denuncia = denuncia;
        dusu.denuncias = denuncias;
        dusu.colacpusu = colacpusu;
        dusu.colatotal = colatotal;

        modDen.usu = usu;
        modDen.lt = lt;
        modDen.denuncia = denuncia;
        modDen.denuncias = denuncias;
        modDen.colacpusu = colacpusu;
        modDen.colatotal = colatotal;

        elimDen.usu = usu;
        elimDen.lt = lt;
        elimDen.denuncia = denuncia;
        elimDen.denuncias = denuncias;
        elimDen.colacpusu = colacpusu;
        elimDen.colatotal = colatotal;

        Contenido.removeAll();
        Contenido.add(modDen, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();

    }//GEN-LAST:event_btnModificarDenunciasMousePressed

    private void btnModificarDenunciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarDenunciasMouseEntered
        // TODO add your handling code here:
        if (btnModificarDenuncias.getBackground().getRGB() == -15574355)
            setColor(btnModificarDenuncias);
    }//GEN-LAST:event_btnModificarDenunciasMouseEntered

    private void btnModificarDenunciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarDenunciasMouseExited
        // TODO add your handling code here:
        if (btnPrincipal.getBackground().getRGB() != -15574355 || btnVerCasos.getBackground().getRGB() != -15574355
                || btnCrearDenuncia.getBackground().getRGB() != -15574355 || btnEliminarDenuncia.getBackground().getRGB() != -15574355)
            resetColor(btnModificarDenuncias);
    }//GEN-LAST:event_btnModificarDenunciasMouseExited

    private void btnEliminarDenunciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarDenunciaMousePressed
        // TODO add your handling code here:
        DenunciaUsuario dusu = new DenunciaUsuario();
        MostrarDenunciasUsuario mdu = new MostrarDenunciasUsuario();
        ModificarDenuncia modDen = new ModificarDenuncia();
        EliminarDenunciaUsuario elimDen = new EliminarDenunciaUsuario();

        resetColor(btnPrincipal);
        resetColor(btnCrearDenuncia);
        resetColor(btnVerCasos);
        resetColor(btnModificarDenuncias);
        setColor(btnEliminarDenuncia);
        ubicacion.setText("Usuario/Menu/Eliminar Denuncia");

        elimDen.setSize(750, 460);
        elimDen.setLocation(0, 0);

        mdu.usu = usu;
        mdu.lt = lt;
        mdu.denuncia = denuncia;
        mdu.denuncias = denuncias;
        mdu.colacpusu = colacpusu;
        mdu.colatotal = colatotal;

        dusu.usu = usu;
        dusu.lt = lt;
        dusu.denuncia = denuncia;
        dusu.denuncias = denuncias;
        dusu.colacpusu = colacpusu;
        dusu.colatotal = colatotal;

        modDen.usu = usu;
        modDen.lt = lt;
        modDen.denuncia = denuncia;
        modDen.denuncias = denuncias;
        modDen.colacpusu = colacpusu;
        modDen.colatotal = colatotal;

        elimDen.usu = usu;
        elimDen.lt = lt;
        elimDen.denuncia = denuncia;
        elimDen.denuncias = denuncias;
        elimDen.colacpusu = colacpusu;
        elimDen.colatotal = colatotal;

        Contenido.removeAll();
        Contenido.add(elimDen, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_btnEliminarDenunciaMousePressed

    private void btnEliminarDenunciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarDenunciaMouseEntered
        // TODO add your handling code here:
        if (btnEliminarDenuncia.getBackground().getRGB() == -15574355)
            setColor(btnEliminarDenuncia);
    }//GEN-LAST:event_btnEliminarDenunciaMouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void btnEliminarDenunciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarDenunciaMouseExited
        // TODO add your handling code here:
        if (btnPrincipal.getBackground().getRGB() != -15574355 || btnVerCasos.getBackground().getRGB() != -15574355
                || btnCrearDenuncia.getBackground().getRGB() != -15574355 || btnModificarDenuncias.getBackground().getRGB() != -15574355)
            resetColor(btnEliminarDenuncia);
    }//GEN-LAST:event_btnEliminarDenunciaMouseExited

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        // TODO add your handling code here:
        Login lg = new Login();
        lg.usu = null;
        lg.lt = lt;
        lg.denuncia = denuncia;
        lg.denuncias = denuncias;
        lg.colacpusu=colacpusu;
        lg.colatotal = colatotal;
        lg.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnLogOutMouseClicked

    /**
     * @param args the command line arguments
     */
    void setColor(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel CuadroCerrado;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Slogan;
    private javax.swing.JPanel Tittle;
    private javax.swing.JPanel btnCrearDenuncia;
    private javax.swing.JPanel btnEliminarDenuncia;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JPanel btnModificarDenuncias;
    private javax.swing.JPanel btnPrincipal;
    private javax.swing.JPanel btnVerCasos;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel txtCerrar;
    private javax.swing.JLabel ubicacion;
    // End of variables declaration//GEN-END:variables
}
