/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Clases.Arbol;
import Clases.ColaConPrioridad;
import Clases.Denuncia;
import Clases.Lista;
import Clases.Usuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;

/**
 *
 * @author rosco
 */
public class MenuPresidente extends javax.swing.JFrame {

    int xMouse, yMouse;
    Usuario usu = new Usuario();
    Lista lt = new Lista();
    Denuncia denuncia = new Denuncia();
    Arbol denuncias = new Arbol();
    DefaultListModel dlm = new DefaultListModel();
    ColaConPrioridad colacpusu = new ColaConPrioridad();
    ColaConPrioridad colatotal = new ColaConPrioridad();
    ColaConPrioridad colaabg = new ColaConPrioridad();

    /**
     * Creates new form Registro
     */
    public MenuPresidente() {
        initComponents();

        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", " ;Septiembre",
            "Octubre", "Noviembre", "Diciemrbre"};
        fecha.setText("Hoy es " + dia + " de " + meses[month - 1] + " de " + year);

        PrincipalPresidente p1 = new PrincipalPresidente();
        p1.setSize(750, 460);
        p1.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(p1, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnPrincipal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnListaDenuncias = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnAsignarCasoAbogado = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bntDisponibilidadAbogados = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnEliminarAbogado = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnListaAbogados = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        ubicacion = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        Tittle = new javax.swing.JPanel();
        CuadroCerrado = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        Slogan = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(13, 71, 161));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SRECJ");
        Menu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));
        Menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, 20));

        btnPrincipal.setBackground(new java.awt.Color(21, 101, 192));
        btnPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrincipalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrincipalMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Principal");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home-outline.png"))); // NOI18N

        javax.swing.GroupLayout btnPrincipalLayout = new javax.swing.GroupLayout(btnPrincipal);
        btnPrincipal.setLayout(btnPrincipalLayout);
        btnPrincipalLayout.setHorizontalGroup(
            btnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPrincipalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        btnPrincipalLayout.setVerticalGroup(
            btnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPrincipalLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(btnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Menu.add(btnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 270, 50));

        btnListaDenuncias.setBackground(new java.awt.Color(18, 90, 173));
        btnListaDenuncias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListaDenunciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaDenunciasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaDenunciasMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ver todas las Denuncias");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_view_details_24px.png"))); // NOI18N

        javax.swing.GroupLayout btnListaDenunciasLayout = new javax.swing.GroupLayout(btnListaDenuncias);
        btnListaDenuncias.setLayout(btnListaDenunciasLayout);
        btnListaDenunciasLayout.setHorizontalGroup(
            btnListaDenunciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaDenunciasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        btnListaDenunciasLayout.setVerticalGroup(
            btnListaDenunciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaDenunciasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(btnListaDenunciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel6))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        Menu.add(btnListaDenuncias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, 50));

        btnAsignarCasoAbogado.setBackground(new java.awt.Color(18, 90, 173));
        btnAsignarCasoAbogado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAsignarCasoAbogadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAsignarCasoAbogadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAsignarCasoAbogadoMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Asignar Caso Abogado");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_assignment_return_24px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnAsignarCasoAbogadoLayout = new javax.swing.GroupLayout(btnAsignarCasoAbogado);
        btnAsignarCasoAbogado.setLayout(btnAsignarCasoAbogadoLayout);
        btnAsignarCasoAbogadoLayout.setHorizontalGroup(
            btnAsignarCasoAbogadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAsignarCasoAbogadoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAsignarCasoAbogadoLayout.setVerticalGroup(
            btnAsignarCasoAbogadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAsignarCasoAbogadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnAsignarCasoAbogadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7))
                .addGap(74, 74, 74))
        );

        Menu.add(btnAsignarCasoAbogado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 50));

        bntDisponibilidadAbogados.setBackground(new java.awt.Color(18, 90, 173));
        bntDisponibilidadAbogados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntDisponibilidadAbogadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntDisponibilidadAbogadosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bntDisponibilidadAbogadosMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ver disponibilidad Abogados");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_batch_assign_24px.png"))); // NOI18N

        javax.swing.GroupLayout bntDisponibilidadAbogadosLayout = new javax.swing.GroupLayout(bntDisponibilidadAbogados);
        bntDisponibilidadAbogados.setLayout(bntDisponibilidadAbogadosLayout);
        bntDisponibilidadAbogadosLayout.setHorizontalGroup(
            bntDisponibilidadAbogadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bntDisponibilidadAbogadosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        bntDisponibilidadAbogadosLayout.setVerticalGroup(
            bntDisponibilidadAbogadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bntDisponibilidadAbogadosLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(bntDisponibilidadAbogadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8))
                .addGap(15, 15, 15))
        );

        Menu.add(bntDisponibilidadAbogados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, 50));

        btnEliminarAbogado.setBackground(new java.awt.Color(18, 90, 173));
        btnEliminarAbogado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarAbogadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarAbogadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarAbogadoMousePressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Eliminar Abogado");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_delete_user_male_24px.png"))); // NOI18N

        javax.swing.GroupLayout btnEliminarAbogadoLayout = new javax.swing.GroupLayout(btnEliminarAbogado);
        btnEliminarAbogado.setLayout(btnEliminarAbogadoLayout);
        btnEliminarAbogadoLayout.setHorizontalGroup(
            btnEliminarAbogadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarAbogadoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        btnEliminarAbogadoLayout.setVerticalGroup(
            btnEliminarAbogadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarAbogadoLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(btnEliminarAbogadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24))
                .addGap(15, 15, 15))
        );

        Menu.add(btnEliminarAbogado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 270, 50));

        btnListaAbogados.setBackground(new java.awt.Color(18, 90, 173));
        btnListaAbogados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListaAbogadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaAbogadosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaAbogadosMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ver todos los Abogados");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Users_24px.png"))); // NOI18N

        javax.swing.GroupLayout btnListaAbogadosLayout = new javax.swing.GroupLayout(btnListaAbogados);
        btnListaAbogados.setLayout(btnListaAbogadosLayout);
        btnListaAbogadosLayout.setHorizontalGroup(
            btnListaAbogadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaAbogadosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        btnListaAbogadosLayout.setVerticalGroup(
            btnListaAbogadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaAbogadosLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(btnListaAbogadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9))
                .addGap(15, 15, 15))
        );

        Menu.add(btnListaAbogados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 270, 50));
        Menu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 250, 10));

        jLabel15.setFont(new java.awt.Font("Roboto Black", 1, 60)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 0));
        jLabel15.setText("CI");
        Menu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, 50));

        jLabel16.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DHU");
        Menu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 130, 50));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        Menu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 250, 10));

        jLabel17.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 0));
        jLabel17.setText("Comité Comisionado Internacional");
        Menu.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 250, -1));

        jLabel14.setFont(new java.awt.Font("Roboto Medium", 1, 23)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DERECHOS HUMANOS");
        Menu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 640));

        Header.setBackground(new java.awt.Color(25, 118, 210));

        ubicacion.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ubicacion.setForeground(new java.awt.Color(255, 255, 255));
        ubicacion.setText("Presidente/Menu/Principal");

        fecha.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("Hoy es Sábado 28 de Abril de 2022");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha)
                    .addComponent(ubicacion))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ubicacion)
                .addGap(27, 27, 27)
                .addComponent(fecha)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        Background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 750, 120));

        Tittle.setBackground(new java.awt.Color(255, 255, 255));
        Tittle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TittleMouseDragged(evt);
            }
        });
        Tittle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TittleMousePressed(evt);
            }
        });

        CuadroCerrado.setBackground(new java.awt.Color(255, 255, 255));

        txtCerrar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CuadroCerradoLayout = new javax.swing.GroupLayout(CuadroCerrado);
        CuadroCerrado.setLayout(CuadroCerradoLayout);
        CuadroCerradoLayout.setHorizontalGroup(
            CuadroCerradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );
        CuadroCerradoLayout.setVerticalGroup(
            CuadroCerradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TittleLayout = new javax.swing.GroupLayout(Tittle);
        Tittle.setLayout(TittleLayout);
        TittleLayout.setHorizontalGroup(
            TittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TittleLayout.createSequentialGroup()
                .addGap(0, 991, Short.MAX_VALUE)
                .addComponent(CuadroCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TittleLayout.setVerticalGroup(
            TittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TittleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CuadroCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Background.add(Tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 30));

        Slogan.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        Slogan.setText("Comprometidos con los derechos humanos y la sociedad!");
        Background.add(Slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        Contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        Background.add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 750, 460));

        btnLogOut.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Logout_Rounded_Left_24px_1.png"))); // NOI18N
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        Background.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TittleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TittleMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_TittleMousePressed

    private void TittleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TittleMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_TittleMouseDragged

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        // TODO add your handling code here:
        CuadroCerrado.setBackground(Color.red);
        txtCerrar.setForeground(Color.white);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        // TODO add your handling code here:
        CuadroCerrado.setBackground(Color.white);
        txtCerrar.setForeground(Color.black);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void btnPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMouseEntered
        // TODO add your handling code here:
        if (btnPrincipal.getBackground().getRGB() == -15574355) {
            setColor(btnPrincipal);
        }

    }//GEN-LAST:event_btnPrincipalMouseEntered

    private void btnPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMousePressed
        // TODO add your handling code here:
        setColor(btnPrincipal);
        resetColor(btnListaDenuncias);
        resetColor(btnAsignarCasoAbogado);
        resetColor(bntDisponibilidadAbogados);
        resetColor(btnEliminarAbogado);
        resetColor(btnListaAbogados);
        ubicacion.setText("Presidente/Menu/Principal");
        PrincipalPresidente p1 = new PrincipalPresidente();
        p1.setSize(750, 460);
        p1.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(p1, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_btnPrincipalMousePressed

    private void btnPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMouseExited
        // TODO add your handling code here:
        if (btnListaDenuncias.getBackground().getRGB() != -15574355 || bntDisponibilidadAbogados.getBackground().getRGB() != -15574355
                || btnAsignarCasoAbogado.getBackground().getRGB() != -15574355 || bntDisponibilidadAbogados.getBackground().getRGB() != -15574355
                || btnListaAbogados.getBackground().getRGB() != -15574355 )
            resetColor(btnPrincipal);
    }//GEN-LAST:event_btnPrincipalMouseExited

    private void btnListaDenunciasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaDenunciasMousePressed
        // TODO add your handling code here:
        MostrarDenunciasPresidente mdP = new MostrarDenunciasPresidente();
        MostrarAbogados mAp = new MostrarAbogados();
        EliminarAbogado elimAbg = new EliminarAbogado();
        AsignarCasoAbogado acA = new AsignarCasoAbogado();
        mostrarDisponibilidadAbogados mda = new mostrarDisponibilidadAbogados();
        resetColor(btnPrincipal);
        setColor(btnListaDenuncias);
        resetColor(btnAsignarCasoAbogado);
        resetColor(bntDisponibilidadAbogados);
        resetColor(btnEliminarAbogado);
        resetColor(btnListaAbogados);
        ubicacion.setText("Presidente/Menu/Todas las Denuncias");

        mdP.usu = usu;
        mdP.lt = lt;
        mdP.denuncia = denuncia;
        mdP.denuncias = denuncias;
        mdP.colaabg = colaabg;
        mdP.colacpusu = colacpusu;
        mdP.colatotal = colatotal;

        elimAbg.usu = usu;
        elimAbg.lt = lt;
        elimAbg.denuncia = denuncia;
        elimAbg.denuncias = denuncias;
        elimAbg.colacpusu = colacpusu;
        elimAbg.colaabg = colaabg;
        elimAbg.colatotal = colatotal;

        mAp.usu = usu;
        mAp.lt = lt;
        mAp.denuncia = denuncia;
        mAp.denuncias = denuncias;
        mAp.colacpusu = colacpusu;
        mAp.colaabg = colaabg;
        mAp.colatotal = colatotal;

        acA.usu = usu;
        acA.lt = lt;
        acA.denuncia = denuncia;
        acA.denuncias = denuncias;
        acA.colaabg = colaabg;
        acA.colacpusu = colacpusu;
        acA.colatotal = colatotal;
        
                mda.usu = usu;
        mda.lt = lt;
        mda.denuncia = denuncia;
        mda.denuncias = denuncias;
        mda.colaabg = colaabg;
        mda.colacpusu = colacpusu;
        mda.colatotal = colatotal;

        mdP.setSize(750, 460);
        mdP.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(mdP, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();

    }//GEN-LAST:event_btnListaDenunciasMousePressed

    private void btnListaDenunciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaDenunciasMouseEntered
        // TODO add your handling code here:
        if (btnListaDenuncias.getBackground().getRGB() == -15574355)
            setColor(btnListaDenuncias);
    }//GEN-LAST:event_btnListaDenunciasMouseEntered

    private void btnListaDenunciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaDenunciasMouseExited
        // TODO add your handling code here:
        if (btnPrincipal.getBackground().getRGB() != -15574355 || bntDisponibilidadAbogados.getBackground().getRGB() != -15574355
                || btnAsignarCasoAbogado.getBackground().getRGB() != -15574355 || bntDisponibilidadAbogados.getBackground().getRGB() != -15574355
                || btnListaAbogados.getBackground().getRGB() != -15574355 )
            resetColor(btnListaDenuncias);
    }//GEN-LAST:event_btnListaDenunciasMouseExited

    private void btnAsignarCasoAbogadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarCasoAbogadoMousePressed
        // TODO add your handling code here:
        MostrarDenunciasPresidente mdP = new MostrarDenunciasPresidente();
        MostrarAbogados mAp = new MostrarAbogados();
        EliminarAbogado elimAbg = new EliminarAbogado();
        AsignarCasoAbogado acA = new AsignarCasoAbogado();
        mostrarDisponibilidadAbogados mda = new mostrarDisponibilidadAbogados();
        resetColor(btnPrincipal);
        resetColor(btnListaDenuncias);
        setColor(btnAsignarCasoAbogado);
        resetColor(bntDisponibilidadAbogados);
        resetColor(btnEliminarAbogado);
        resetColor(btnListaAbogados);
        ubicacion.setText("Presidente/Menu/Asignar Caso Abogado");

        mdP.usu = usu;
        mdP.lt = lt;
        mdP.denuncia = denuncia;
        mdP.denuncias = denuncias;
        mdP.colaabg = colaabg;
        mdP.colacpusu = colacpusu;
        mdP.colatotal = colatotal;

        elimAbg.usu = usu;
        elimAbg.lt = lt;
        elimAbg.denuncia = denuncia;
        elimAbg.denuncias = denuncias;
        elimAbg.colacpusu = colacpusu;
        elimAbg.colaabg = colaabg;
        elimAbg.colatotal = colatotal;

        mAp.usu = usu;
        mAp.lt = lt;
        mAp.denuncia = denuncia;
        mAp.denuncias = denuncias;
        mAp.colacpusu = colacpusu;
        mAp.colaabg = colaabg;
        mAp.colatotal = colatotal;

        acA.usu = usu;
        acA.lt = lt;
        acA.denuncia = denuncia;
        acA.denuncias = denuncias;
        acA.colaabg = colaabg;
        acA.colacpusu = colacpusu;
        acA.colatotal = colatotal;
        
                mda.usu = usu;
        mda.lt = lt;
        mda.denuncia = denuncia;
        mda.denuncias = denuncias;
        mda.colaabg = colaabg;
        mda.colacpusu = colacpusu;
        mda.colatotal = colatotal;

        acA.setSize(750, 460);
        acA.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(acA, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_btnAsignarCasoAbogadoMousePressed

    private void btnAsignarCasoAbogadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarCasoAbogadoMouseEntered
        // TODO add your handling code here:
        if (btnAsignarCasoAbogado.getBackground().getRGB() == -15574355)
            setColor(btnAsignarCasoAbogado);
    }//GEN-LAST:event_btnAsignarCasoAbogadoMouseEntered

    private void btnAsignarCasoAbogadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarCasoAbogadoMouseExited
        // TODO add your handling code here:
        if (btnListaDenuncias.getBackground().getRGB() != -15574355 || bntDisponibilidadAbogados.getBackground().getRGB() != -15574355
                || btnPrincipal.getBackground().getRGB() != -15574355 || bntDisponibilidadAbogados.getBackground().getRGB() != -15574355
                || btnListaAbogados.getBackground().getRGB() != -15574355 )
            resetColor(btnAsignarCasoAbogado);
    }//GEN-LAST:event_btnAsignarCasoAbogadoMouseExited

    private void bntDisponibilidadAbogadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntDisponibilidadAbogadosMousePressed
        // TODO add your handling code here:
        MostrarDenunciasPresidente mdP = new MostrarDenunciasPresidente();
        MostrarAbogados mAp = new MostrarAbogados();
        EliminarAbogado elimAbg = new EliminarAbogado();
        AsignarCasoAbogado acA = new AsignarCasoAbogado();
        mostrarDisponibilidadAbogados mda = new mostrarDisponibilidadAbogados();
        
        resetColor(btnPrincipal);
        resetColor(btnListaDenuncias);
        resetColor(btnAsignarCasoAbogado);
        setColor(bntDisponibilidadAbogados);
        resetColor(btnEliminarAbogado);
        resetColor(btnListaAbogados);
        ubicacion.setText("Presidente/Menu/Ver Disponibilidad Abogados");

        mdP.usu = usu;
        mdP.lt = lt;
        mdP.denuncia = denuncia;
        mdP.denuncias = denuncias;
        mdP.colaabg = colaabg;
        mdP.colacpusu = colacpusu;
        mdP.colatotal = colatotal;

        elimAbg.usu = usu;
        elimAbg.lt = lt;
        elimAbg.denuncia = denuncia;
        elimAbg.denuncias = denuncias;
        elimAbg.colacpusu = colacpusu;
        elimAbg.colaabg = colaabg;
        elimAbg.colatotal = colatotal;

        mAp.usu = usu;
        mAp.lt = lt;
        mAp.denuncia = denuncia;
        mAp.denuncias = denuncias;
        mAp.colacpusu = colacpusu;
        mAp.colaabg = colaabg;
        mAp.colatotal = colatotal;

        acA.usu = usu;
        acA.lt = lt;
        acA.denuncia = denuncia;
        acA.denuncias = denuncias;
        acA.colaabg = colaabg;
        acA.colacpusu = colacpusu;
        acA.colatotal = colatotal;
        
        mda.usu = usu;
        mda.lt = lt;
        mda.denuncia = denuncia;
        mda.denuncias = denuncias;
        mda.colaabg = colaabg;
        mda.colacpusu = colacpusu;
        mda.colatotal = colatotal;

        mda.setSize(750, 460);
        mda.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(mda, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_bntDisponibilidadAbogadosMousePressed

    private void bntDisponibilidadAbogadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntDisponibilidadAbogadosMouseEntered
        // TODO add your handling code here:
        if (bntDisponibilidadAbogados.getBackground().getRGB() == -15574355)
            setColor(bntDisponibilidadAbogados);
    }//GEN-LAST:event_bntDisponibilidadAbogadosMouseEntered

    private void bntDisponibilidadAbogadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntDisponibilidadAbogadosMouseExited
        // TODO add your handling code here:
        if (btnListaDenuncias.getBackground().getRGB() != -15574355 || btnAsignarCasoAbogado.getBackground().getRGB() != -15574355
                || btnPrincipal.getBackground().getRGB() != -15574355 || bntDisponibilidadAbogados.getBackground().getRGB() != -15574355
                || btnListaAbogados.getBackground().getRGB() != -15574355)
            resetColor(bntDisponibilidadAbogados);
    }//GEN-LAST:event_bntDisponibilidadAbogadosMouseExited

    private void btnEliminarAbogadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarAbogadoMouseEntered
        // TODO add your handling code here:
        if (btnEliminarAbogado.getBackground().getRGB() == -15574355)
            setColor(btnEliminarAbogado);
    }//GEN-LAST:event_btnEliminarAbogadoMouseEntered

    private void btnEliminarAbogadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarAbogadoMouseExited
        // TODO add your handling code here:
        if (btnListaDenuncias.getBackground().getRGB() != -15574355 || btnAsignarCasoAbogado.getBackground().getRGB() != -15574355
                || btnPrincipal.getBackground().getRGB() != -15574355 || bntDisponibilidadAbogados.getBackground().getRGB() != -15574355
                || btnListaAbogados.getBackground().getRGB() != -15574355 )
            resetColor(btnEliminarAbogado);
    }//GEN-LAST:event_btnEliminarAbogadoMouseExited

    private void btnEliminarAbogadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarAbogadoMousePressed
        // TODO add your handling code here:
        MostrarDenunciasPresidente mdP = new MostrarDenunciasPresidente();
        MostrarAbogados mAp = new MostrarAbogados();
        EliminarAbogado elimAbg = new EliminarAbogado();
        AsignarCasoAbogado acA = new AsignarCasoAbogado();
        mostrarDisponibilidadAbogados mda = new mostrarDisponibilidadAbogados();
        resetColor(btnPrincipal);
        resetColor(btnListaDenuncias);
        resetColor(btnAsignarCasoAbogado);
        resetColor(bntDisponibilidadAbogados);
        setColor(btnEliminarAbogado);
        resetColor(btnListaAbogados);
        ubicacion.setText("Presidente/Menu/Eliminar Abogado");

        mdP.usu = usu;
        mdP.lt = lt;
        mdP.denuncia = denuncia;
        mdP.denuncias = denuncias;
        mdP.colaabg = colaabg;
        mdP.colacpusu = colacpusu;
        mdP.colatotal = colatotal;

        elimAbg.usu = usu;
        elimAbg.lt = lt;
        elimAbg.denuncia = denuncia;
        elimAbg.denuncias = denuncias;
        elimAbg.colacpusu = colacpusu;
        elimAbg.colaabg = colaabg;
        elimAbg.colatotal = colatotal;

        mAp.usu = usu;
        mAp.lt = lt;
        mAp.denuncia = denuncia;
        mAp.denuncias = denuncias;
        mAp.colacpusu = colacpusu;
        mAp.colaabg = colaabg;
        mAp.colatotal = colatotal;

        acA.usu = usu;
        acA.lt = lt;
        acA.denuncia = denuncia;
        acA.denuncias = denuncias;
        acA.colaabg = colaabg;
        acA.colacpusu = colacpusu;
        acA.colatotal = colatotal;
        
        mda.usu = usu;
        mda.lt = lt;
        mda.denuncia = denuncia;
        mda.denuncias = denuncias;
        mda.colaabg = colaabg;
        mda.colacpusu = colacpusu;
        mda.colatotal = colatotal;

        elimAbg.setSize(750, 460);
        elimAbg.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(elimAbg, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_btnEliminarAbogadoMousePressed

    private void btnListaAbogadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaAbogadosMouseEntered
        // TODO add your handling code here:
        if (btnListaAbogados.getBackground().getRGB() == -15574355)
            setColor(btnListaAbogados);
    }//GEN-LAST:event_btnListaAbogadosMouseEntered

    private void btnListaAbogadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaAbogadosMouseExited
        // TODO add your handling code here:
        if (btnListaDenuncias.getBackground().getRGB() != -15574355 || btnAsignarCasoAbogado.getBackground().getRGB() != -15574355
                || btnPrincipal.getBackground().getRGB() != -15574355 || bntDisponibilidadAbogados.getBackground().getRGB() != -15574355
                || btnEliminarAbogado.getBackground().getRGB() != -15574355)
            resetColor(btnListaAbogados);
    }//GEN-LAST:event_btnListaAbogadosMouseExited

    private void btnListaAbogadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaAbogadosMousePressed
        // TODO add your handling code here:
        MostrarDenunciasPresidente mdP = new MostrarDenunciasPresidente();
        MostrarAbogados mAp = new MostrarAbogados();
        EliminarAbogado elimAbg = new EliminarAbogado();
        AsignarCasoAbogado acA = new AsignarCasoAbogado();
        mostrarDisponibilidadAbogados mda = new mostrarDisponibilidadAbogados();
        resetColor(btnPrincipal);
        resetColor(btnListaDenuncias);
        resetColor(btnAsignarCasoAbogado);
        resetColor(bntDisponibilidadAbogados);
        resetColor(btnEliminarAbogado);
        setColor(btnListaAbogados);
        ubicacion.setText("Presidente/Menu/Todos los abogados");
        mdP.usu = usu;
        mdP.lt = lt;
        mdP.denuncia = denuncia;
        mdP.denuncias = denuncias;
        mdP.colaabg = colaabg;
        mdP.colacpusu = colacpusu;
        mdP.colatotal = colatotal;

        elimAbg.usu = usu;
        elimAbg.lt = lt;
        elimAbg.denuncia = denuncia;
        elimAbg.denuncias = denuncias;
        elimAbg.colacpusu = colacpusu;
        elimAbg.colaabg = colaabg;
        elimAbg.colatotal = colatotal;

        mAp.usu = usu;
        mAp.lt = lt;
        mAp.denuncia = denuncia;
        mAp.denuncias = denuncias;
        mAp.colacpusu = colacpusu;
        mAp.colaabg = colaabg;
        mAp.colatotal = colatotal;

        acA.usu = usu;
        acA.lt = lt;
        acA.denuncia = denuncia;
        acA.denuncias = denuncias;
        acA.colaabg = colaabg;
        acA.colacpusu = colacpusu;
        
        mda.usu = usu;
        mda.lt = lt;
        mda.denuncia = denuncia;
        mda.denuncias = denuncias;
        mda.colaabg = colaabg;
        mda.colacpusu = colacpusu;
        mda.colatotal = colatotal;

        mAp.setSize(750, 460);
        mAp.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(mAp, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_btnListaAbogadosMousePressed

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        // TODO add your handling code here:
        Login lg = new Login();
        lg.usu = null;
        lg.lt = lt;
        lg.denuncia = denuncia;
        lg.denuncias = denuncias;
        lg.colaabg = colaabg;
        lg.colacpusu = colacpusu;
        lg.colatotal = colatotal;
        lg.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnLogOutMouseClicked

    /**
     * @param args the command line arguments
     */
    void setColor(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPresidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPresidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPresidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPresidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPresidente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel CuadroCerrado;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Slogan;
    private javax.swing.JPanel Tittle;
    private javax.swing.JPanel bntDisponibilidadAbogados;
    private javax.swing.JPanel btnAsignarCasoAbogado;
    private javax.swing.JPanel btnEliminarAbogado;
    private javax.swing.JPanel btnListaAbogados;
    private javax.swing.JPanel btnListaDenuncias;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JPanel btnPrincipal;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel txtCerrar;
    private javax.swing.JLabel ubicacion;
    // End of variables declaration//GEN-END:variables
}
