/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Clases.Arbol;
import Clases.ColaConPrioridad;
import Clases.Denuncia;
import Clases.Lista;
import Clases.Usuario;
import static Interfaz.DenunciaUsuario.getRandomString;
import java.awt.BorderLayout;
import java.awt.Color;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rosco
 */
public class ModificarDenuncia extends javax.swing.JPanel {

    Usuario usu = new Usuario();
    Lista lt = new Lista();
    Denuncia denuncia = new Denuncia();
    Arbol denuncias = new Arbol();
    DefaultListModel dlm = new DefaultListModel();
    ColaConPrioridad colacpusu = new ColaConPrioridad();
    ColaConPrioridad colatotal = new ColaConPrioridad();

    /**
     * Creates new form Princ
     */
    public ModificarDenuncia() {
        initComponents();
        cmbCaracter.setEnabled(false);
        cmbInstancia.setEnabled(false);
        cmbAsistencia.setEnabled(false);
        txtResponsables.setEnabled(false);
        txaCarta.setEnabled(false);
        jListDenuncias.setModel(dlm);
        ArrayList<Denuncia> listado = colacpusu.obtenerTodos();

        Collections.sort(listado);
        for (Denuncia obj : listado) {
            dlm.addElement(obj.toString());
        }
    }

    public void Listar() {
        dlm.removeAllElements();
        //dlm.addElement(denuncias.preOrden());
    }

    void setColor(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }

    public boolean verificarVacio(String texto) {
        return texto.isEmpty();
    }

    static String getRandomString(int i) {

        // bind the length 
        byte[] bytearray;
        bytearray = new byte[256];
        String mystring;
        StringBuffer thebuffer;
        String theAlphaNumericS;

        new Random().nextBytes(bytearray);

        mystring
                = new String(bytearray, Charset.forName("UTF-8"));

        thebuffer = new StringBuffer();

        //remove all spacial char 
        theAlphaNumericS
                = mystring
                        .replaceAll("[^A-Z0-9]", "");

        //random selection
        for (int m = 0; m < theAlphaNumericS.length(); m++) {

            if (Character.isLetter(theAlphaNumericS.charAt(m))
                    && (i > 0)
                    || Character.isDigit(theAlphaNumericS.charAt(m))
                    && (i > 0)) {

                thebuffer.append(theAlphaNumericS.charAt(m));
                i--;
            }
        }

        // the resulting string 
        return thebuffer.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbCaracter = new javax.swing.JComboBox<>();
        cmbAsistencia = new javax.swing.JComboBox<>();
        cmbInstancia = new javax.swing.JComboBox<>();
        txtResponsables = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaCarta = new javax.swing.JTextArea();
        btnRemplazar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListDenuncias = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        Title.setText("INGRESE EL CODIGO DE LA DENUNCIA QUE DESEA REMPLAZAR");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Text1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Text1.setText("Caracter de la denuncia: ");
        jPanel1.add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Instancia de la denuncia:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Asistencia Personal del CIDHU:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        cmbCaracter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Familiar", "Organizacion", "Asociacion", "Institucion", "Grupo", "Empresa", "Estado", "Gobierno Autonomo" }));
        cmbCaracter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCaracterActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCaracter, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 160, 30));

        cmbAsistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));
        cmbAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAsistenciaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 160, 30));

        cmbInstancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Territorial", "Nacional", "Internacional" }));
        cmbInstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbInstanciaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbInstancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 160, 30));
        jPanel1.add(txtResponsables, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 270, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("responsables/autoridad u Institucion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Ingrese una sintesis de los hechos:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        txaCarta.setColumns(20);
        txaCarta.setRows(5);
        jScrollPane1.setViewportView(txaCarta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 480, 30));

        btnRemplazar.setBackground(new java.awt.Color(18, 90, 173));
        btnRemplazar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemplazar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemplazarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRemplazarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRemplazarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRemplazarMousePressed(evt);
            }
        });
        btnRemplazar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Remplazar");
        btnRemplazar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(btnRemplazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 160, 50));

        jScrollPane2.setViewportView(jListDenuncias);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 690, 90));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel7.setText("Estado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel11.setText("Asistencia");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel12.setText("Instancia");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel10.setText("Caracter");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel8.setText("Codigo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel13.setText("Responsables/Carta");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel9.setText("Gravedad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Ingrese el nombre de los ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        Text2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Text2.setText("CODIGO PARA BUSCAR:");
        jPanel1.add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 42, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemplazarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemplazarMouseClicked
        // TODO add your handling code here:
            MenuUsuario mn = new MenuUsuario();
            MostrarDenunciasUsuario mdu = new MostrarDenunciasUsuario();
            ModificarDenuncia modDen = new ModificarDenuncia();
            String random = getRandomString(5);
            int gravedad = denuncia.algoritmoAnaliticoBusquedaPalabrasClave(txaCarta.getText());
            
        if (!colacpusu.esVacia()&& !verificarVacio(txaCarta.getText()) && !verificarVacio(txtResponsables.getText())) {
            //den = new Denuncia((String)cmbCaracter.getSelectedItem(),(String)cmbInstancia.getSelectedItem(),(String)cmbAsistencia.getSelectedItem(),txtResponsables.getText(),txtHechos.getText());
            boolean bandera = colacpusu.actualizarBool(txtCodigo.getText(), new Denuncia((String) cmbCaracter.getSelectedItem(), (String) cmbInstancia.getSelectedItem(), (String) cmbAsistencia.getSelectedItem(), txtResponsables.getText(), txaCarta.getText(), usu.getCedula(), gravedad, "En revision", random ));
            if(bandera){
            
            colacpusu.actualizar(txtCodigo.getText(), new Denuncia((String) cmbCaracter.getSelectedItem(), (String) cmbInstancia.getSelectedItem(), (String) cmbAsistencia.getSelectedItem(), txtResponsables.getText(), txaCarta.getText(), usu.getCedula(), gravedad, "En revision", txtCodigo.getText() ));
            colatotal.actualizar(txtCodigo.getText(),new Denuncia((String) cmbCaracter.getSelectedItem(), (String) cmbInstancia.getSelectedItem(), (String) cmbAsistencia.getSelectedItem(), txtResponsables.getText(), txaCarta.getText(), usu.getCedula(), gravedad, "En revision", txtCodigo.getText() ));
            
            usu.setColaden(colacpusu);
            dlm.removeAllElements();
            ArrayList<Denuncia> listado = colacpusu.obtenerTodos();

            Collections.sort(listado);
            for (Denuncia obj : listado) {
                dlm.addElement(obj.toString());
            }

            mdu.usu = usu;
            mdu.lt = lt;
            mdu.denuncia = denuncia;
            mdu.denuncias = denuncias;
            mdu.colacpusu = colacpusu;
            mdu.colatotal = colatotal;
            
            modDen.usu = usu;
            modDen.lt = lt;
            modDen.denuncia = denuncia;
            modDen.denuncias = denuncias;
            modDen.colacpusu = colacpusu;
            modDen.colatotal = colatotal;

            mn.usu = usu;
            mn.lt = lt;
            mn.denuncia = denuncia;
            mn.denuncias = denuncias;
            mn.colacpusu = colacpusu;
            mn.colatotal = colatotal;
            JOptionPane.showMessageDialog(null, "LA DENUNCIA CON CODIGO "+txtCodigo.getText()+" HA SIDO REMPLAZADA");
            //txaDenuncias.setText(denuncias.mo);
            //Listar();
            }else{
               JOptionPane.showMessageDialog(null, "NO EXISTE EL CODIGO");
            }
        } else {
            JOptionPane.showMessageDialog(null, "ACTUALMENTE NO TIENE DENUNCIAS DISPONIBLES");
        }
    }//GEN-LAST:event_btnRemplazarMouseClicked

    private void btnRemplazarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemplazarMouseEntered
        setColor(btnRemplazar);
    }//GEN-LAST:event_btnRemplazarMouseEntered

    private void btnRemplazarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemplazarMouseExited
        resetColor(btnRemplazar);
    }//GEN-LAST:event_btnRemplazarMouseExited

    private void btnRemplazarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemplazarMousePressed

    }//GEN-LAST:event_btnRemplazarMousePressed

    private void cmbCaracterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCaracterActionPerformed
        // TODO add your handling code here:
        cmbInstancia.setEnabled(true);
    }//GEN-LAST:event_cmbCaracterActionPerformed

    private void cmbInstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInstanciaActionPerformed
        // TODO add your handling code here:
        cmbAsistencia.setEnabled(true);
    }//GEN-LAST:event_cmbInstanciaActionPerformed

    private void cmbAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAsistenciaActionPerformed
        // TODO add your handling code here:
        txtResponsables.setEnabled(true);
        txaCarta.setEnabled(true);
    }//GEN-LAST:event_cmbAsistenciaActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        cmbCaracter.setEnabled(true);
    }//GEN-LAST:event_txtCodigoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel btnRemplazar;
    private javax.swing.JComboBox<String> cmbAsistencia;
    private javax.swing.JComboBox<String> cmbCaracter;
    private javax.swing.JComboBox<String> cmbInstancia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListDenuncias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txaCarta;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtResponsables;
    // End of variables declaration//GEN-END:variables
}
