/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Clases.Arbol;
import Clases.ColaConPrioridad;
import Clases.Denuncia;
import Clases.Lista;
import Clases.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rosco
 */
public class MostrarAbogados extends javax.swing.JPanel {

    Usuario usu = new Usuario();
    Lista lt = new Lista();
    Denuncia denuncia = new Denuncia();
    Arbol denuncias = new Arbol();
    DefaultListModel dlm = new DefaultListModel();
    ColaConPrioridad colacpusu = new ColaConPrioridad();
    ColaConPrioridad colatotal = new ColaConPrioridad();
    ColaConPrioridad colaabg = new ColaConPrioridad();
    

    /**
     * Creates new form Princ
     */
    public MostrarAbogados() {
        initComponents();
        jListAbogados.setModel(dlm);
        ArrayList<Denuncia> listado = colatotal.obtenerTodos();

        Collections.sort(listado);
        for (Denuncia obj : listado) {
            dlm.addElement(obj.toString());
        }
    }

        public void Listar1(String tipo){
        dlm.removeAllElements();
        for (Usuario asuarioab : lt.getComponente()) {
            if(tipo.equals(asuarioab.getTipo())){
            dlm.addElement(asuarioab.toStringAbg());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAbogados = new javax.swing.JList<>();
        btnMostrar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        Title.setText("Todos los abogados registrados");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Bienvenido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Estos son los miembros del comite del CIDHU");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jScrollPane1.setViewportView(jListAbogados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 690, 190));

        btnMostrar.setBackground(new java.awt.Color(18, 90, 173));
        btnMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrarMousePressed(evt);
            }
        });
        btnMostrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Listar Abogados");
        btnMostrar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 160, 50));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setText("Disponibilidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setText("Nombre/Apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel8.setText("Casos Asignados");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setText("Correo Electronico");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseClicked
        // TODO add your handling code here:
        MenuPresidente mP = new MenuPresidente();
        if (!lt.esVacia()) {
            //den = new Denuncia((String)cmbCaracter.getSelectedItem(),(String)cmbInstancia.getSelectedItem(),(String)cmbAsistencia.getSelectedItem(),txtResponsables.getText(),txtHechos.getText());
            //colacpusu.encolar(new Denuncia((String) cmbCaracter.getSelectedItem(), (String) cmbAsistencia.getSelectedItem(), (String) cmbAsistencia.getSelectedItem(), txtResponsables.getText(), txaCarta.getText(), usu.getCedula(), gravedad, "En revision"));
            //colatotal.encolar(new Denuncia((String) cmbCaracter.getSelectedItem(), (String) cmbAsistencia.getSelectedItem(), (String) cmbAsistencia.getSelectedItem(), txtResponsables.getText(), txaCarta.getText(), usu.getCedula(), gravedad, "En revision"));
            //usu.setColaden(colacpusu);
            dlm.removeAllElements();
            Listar1("Abogado");

            mP.usu = usu;
            mP.lt = lt;
            mP.denuncia = denuncia;
            mP.denuncias = denuncias;
            mP.colacpusu =colacpusu;
            mP.colatotal = colatotal;

            //txaDenuncias.setText(denuncias.mo);
            //Listar();
        } else {
            JOptionPane.showMessageDialog(null, "ACTUALMENTE NO TIENE DENUNCIAS DISPONIBLES");
        }
    }//GEN-LAST:event_btnMostrarMouseClicked

    private void btnMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseEntered
        setColor(btnMostrar);
    }//GEN-LAST:event_btnMostrarMouseEntered

    private void btnMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseExited
        resetColor(btnMostrar);
    }//GEN-LAST:event_btnMostrarMouseExited

    private void btnMostrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMousePressed

    }//GEN-LAST:event_btnMostrarMousePressed

    void setColor(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListAbogados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
