/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Clases.Arbol;
import Clases.ColaConPrioridad;
import Clases.Denuncia;
import Clases.Lista;
import Clases.Usuario;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.commons.validator.EmailValidator;

/**
 *
 * @author rosco
 */
public class Registro extends javax.swing.JFrame {
    Usuario usu = new Usuario();
    Lista lt = new Lista();
    Denuncia denuncia = new Denuncia();
    Arbol denuncias = new Arbol();
    ColaConPrioridad colacpusu = new ColaConPrioridad();
    ColaConPrioridad colatotal = new ColaConPrioridad();
    ColaConPrioridad colaabg = new ColaConPrioridad();
    int xMouse, yMouse;

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        txtCedula.setEnabled(false);
        txtCorreo.setEnabled(false);
        txtPassword.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtCodigoGerencia.setEnabled(false);
        txtCredencial.setEnabled(false);
        btnRegistrar.setEnabled(false);
        lbl_avisoNombre.setVisible(false);
        lbl_avisoApellido.setVisible(false);
        lbl_avisoCorreo.setVisible(false);
        lbl_avisoClave.setVisible(false);
        lbl_avisoCedula.setVisible(false);
        lbl_avisoTelefono.setVisible(false);
        lbl_avisoCredencial.setVisible(false);
        lbl_avisoCodigo.setVisible(false);
    }

    public boolean verificar_Clave(String correo) {
        Pattern patron = Pattern.compile("^(?=\\w*\\d)(?=\\w*[A-Z])(?=\\w*[a-z])\\S{8,16}$");

        Matcher mat = patron.matcher(correo);
        return mat.find();
    }

    public boolean verificarVacio(String texto) {
        return texto.isEmpty();
    }

    public boolean verificarCedulaTelefono(String numeros) {
        Pattern patron = Pattern.compile("^(?=\\w*[0-9])\\S{10}$");

        Matcher mat = patron.matcher(numeros);
        return mat.find();
    }

    public boolean verificarCredencial(String credencial) {
        String validacion = txtCedula.getText().concat("004");
        return validacion.equals(credencial);
    }

    public boolean verificarCodigo(String codigo) {

        return codigo.equals("0403") || codigo.equals("0402") || codigo.equals("0401") || codigo.equals("0404") || codigo.equals("0405") || codigo.equals("0406") || codigo.equals("0407");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Text5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lblCredencial = new javax.swing.JLabel();
        txtCredencial = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lblCodigoGerencia = new javax.swing.JLabel();
        txtCodigoGerencia = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        lbl_avisoNombre = new javax.swing.JLabel();
        lbl_avisoApellido = new javax.swing.JLabel();
        lbl_avisoCorreo = new javax.swing.JLabel();
        lbl_avisoClave = new javax.swing.JLabel();
        lbl_avisoCedula = new javax.swing.JLabel();
        lbl_avisoTelefono = new javax.swing.JLabel();
        lbl_avisoCredencial = new javax.swing.JLabel();
        lbl_avisoCodigo = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        Text7 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        datosQuemados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        Title.setText("Registrar nuevo Usuario");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Text1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Text1.setText("Teléfono");
        jPanel1.add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        Text2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Text2.setText("Cedula");
        jPanel1.add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 260, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 260, 10));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 10, 460));

        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefono.setText("Ingrese un número telefónico");
        txtTelefono.setBorder(null);
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 260, 30));

        txtCedula.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(102, 102, 102));
        txtCedula.setText("Ingresa tu cedula");
        txtCedula.setBorder(null);
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaMousePressed(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 260, 30));

        btnRegistrar.setBackground(new java.awt.Color(18, 90, 173));
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegistrarMousePressed(evt);
            }
        });
        btnRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar");
        btnRegistrar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 160, 50));

        Text3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Text3.setText("Nombre");
        jPanel1.add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        txtNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setText("Ingrese el nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 260, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 260, 10));

        Text4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Text4.setText("Apellido");
        jPanel1.add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txtApellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtApellido.setText("Ingrese el apellido paterno");
        txtApellido.setBorder(null);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 260, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 260, 10));

        Text5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Text5.setText("Contraseña");
        jPanel1.add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 260, 10));

        Text6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Text6.setText("Email");
        jPanel1.add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(102, 102, 102));
        txtCorreo.setText("Ingrese el correo electronico");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 260, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 260, 10));

        lblCredencial.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblCredencial.setText("Credencial");
        jPanel1.add(lblCredencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        txtCredencial.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCredencial.setForeground(new java.awt.Color(102, 102, 102));
        txtCredencial.setText("Ingrese su credencial asignada");
        txtCredencial.setBorder(null);
        txtCredencial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCredencialMousePressed(evt);
            }
        });
        txtCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCredencialActionPerformed(evt);
            }
        });
        txtCredencial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCredencialKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCredencialKeyTyped(evt);
            }
        });
        jPanel1.add(txtCredencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 260, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 260, 10));

        lblCodigoGerencia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblCodigoGerencia.setText("Codigo Gerencia");
        jPanel1.add(lblCodigoGerencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        txtCodigoGerencia.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCodigoGerencia.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoGerencia.setText("Ingrese el codigo entregado por gerencia");
        txtCodigoGerencia.setBorder(null);
        txtCodigoGerencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoGerenciaMousePressed(evt);
            }
        });
        txtCodigoGerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoGerenciaActionPerformed(evt);
            }
        });
        txtCodigoGerencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoGerenciaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoGerenciaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigoGerencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 260, 30));

        jSeparator9.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 260, 10));

        btnCancelar.setBackground(new java.awt.Color(18, 90, 173));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
        });
        btnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cancelar");
        btnCancelar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 160, 50));

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));

        txtCerrar.setFont(new java.awt.Font("Roboto Light", 0, 28)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCerrarLayout = new javax.swing.GroupLayout(btnCerrar);
        btnCerrar.setLayout(btnCerrarLayout);
        btnCerrarLayout.setHorizontalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnCerrarLayout.setVerticalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 50, 40));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 40));

        lbl_avisoNombre.setFont(new java.awt.Font("Roboto", 1, 8)); // NOI18N
        lbl_avisoNombre.setForeground(new java.awt.Color(255, 51, 51));
        lbl_avisoNombre.setText("CAMPO VACIO (*)");
        jPanel1.add(lbl_avisoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        lbl_avisoApellido.setFont(new java.awt.Font("Roboto", 1, 8)); // NOI18N
        lbl_avisoApellido.setForeground(new java.awt.Color(255, 51, 51));
        lbl_avisoApellido.setText("CAMPO VACIO (*)");
        jPanel1.add(lbl_avisoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        lbl_avisoCorreo.setFont(new java.awt.Font("Roboto", 1, 8)); // NOI18N
        lbl_avisoCorreo.setForeground(new java.awt.Color(255, 51, 51));
        lbl_avisoCorreo.setText("EMAIL INVALIDO(*)");
        jPanel1.add(lbl_avisoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        lbl_avisoClave.setFont(new java.awt.Font("Roboto", 1, 8)); // NOI18N
        lbl_avisoClave.setForeground(new java.awt.Color(255, 51, 51));
        lbl_avisoClave.setText("CONTRASEÑA  INVALIDA(*)");
        jPanel1.add(lbl_avisoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        lbl_avisoCedula.setFont(new java.awt.Font("Roboto", 1, 8)); // NOI18N
        lbl_avisoCedula.setForeground(new java.awt.Color(255, 51, 51));
        lbl_avisoCedula.setText("CEDULA INVALIDA(*)");
        jPanel1.add(lbl_avisoCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        lbl_avisoTelefono.setFont(new java.awt.Font("Roboto", 1, 8)); // NOI18N
        lbl_avisoTelefono.setForeground(new java.awt.Color(255, 51, 51));
        lbl_avisoTelefono.setText("TELEFONO INVALIDO(*)");
        jPanel1.add(lbl_avisoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        lbl_avisoCredencial.setFont(new java.awt.Font("Roboto", 1, 8)); // NOI18N
        lbl_avisoCredencial.setForeground(new java.awt.Color(255, 51, 51));
        lbl_avisoCredencial.setText("CREDENCIAL INVALIDA(*)");
        jPanel1.add(lbl_avisoCredencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        lbl_avisoCodigo.setFont(new java.awt.Font("Roboto", 1, 8)); // NOI18N
        lbl_avisoCodigo.setForeground(new java.awt.Color(255, 51, 51));
        lbl_avisoCodigo.setText("CODIGO INVALIDO(*)");
        jPanel1.add(lbl_avisoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));

        txtPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtPassword.setText("********************");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasswordMousePressed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 260, 30));

        Text7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Text7.setText("Tipo de Usuario");
        jPanel1.add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Comun", "Abogado" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 100, -1));

        datosQuemados.setText("DATOS QUEMADOS");
        datosQuemados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datosQuemadosMouseClicked(evt);
            }
        });
        datosQuemados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosQuemadosActionPerformed(evt);
            }
        });
        jPanel1.add(datosQuemados, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        if (txtNombre.getText().equals("") || txtNombre.getText() == null || txtNombre.getText().equals(" ")) {
            txtNombre.setText("Ingrese el nombre");
        }
        if (txtApellido.getText().equals("") || txtApellido.getText() == null || txtApellido.getText().equals(" ")) {
            txtApellido.setText("Ingrese el apellido paterno");
        }
        if (String.valueOf(txtPassword.getPassword()).equals("") || txtPassword.getPassword() == null || String.valueOf(txtPassword.getPassword()).equals(" ")) {
            txtPassword.setText("********************");
        }
        if (txtCedula.getText().equals("") || txtCedula.getText() == null || txtCedula.getText().equals(" ")) {
            txtCedula.setText("Ingresa tu cedula");
        }
        if (txtCorreo.getText().equals("") || txtCorreo.getText() == null || txtCorreo.getText().equals(" ")) {
            txtCorreo.setText("Ingrese el correo electronico");
        }
        if (txtCredencial.getText().equals("") || txtCredencial.getText() == null || txtCredencial.getText().equals(" ")) {
            txtCredencial.setText("Ingrese su credencial asignada");
        }
        if (txtCodigoGerencia.getText().equals("") || txtCodigoGerencia.getText() == null || txtCodigoGerencia.getText().equals(" ")) {
            txtCodigoGerencia.setText("Ingrese el codigo entregado por gerencia");
        }
        if (txtTelefono.getText().equals("Ingrese un número telefónico"))
            txtTelefono.setText("");
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMousePressed
        if (txtNombre.getText().equals("") || txtNombre.getText() == null || txtNombre.getText().equals(" ")) {
            txtNombre.setText("Ingrese el nombre");
        }
        if (txtApellido.getText().equals("") || txtApellido.getText() == null || txtApellido.getText().equals(" ")) {
            txtApellido.setText("Ingrese el apellido paterno");
        }
        if (String.valueOf(txtPassword.getPassword()).equals("") || txtPassword.getPassword() == null || String.valueOf(txtPassword.getPassword()).equals(" ")) {
            txtPassword.setText("********************");
        }
        if (txtTelefono.getText().equals("") || txtTelefono.getText() == null || txtTelefono.getText().equals(" ")) {
            txtTelefono.setText("Ingrese un número telefónico");
        }
        if (txtCorreo.getText().equals("") || txtCorreo.getText() == null || txtCorreo.getText().equals(" ")) {
            txtCorreo.setText("Ingrese el correo electronico");
        }
        if (txtCredencial.getText().equals("") || txtCredencial.getText() == null || txtCredencial.getText().equals(" ")) {
            txtCredencial.setText("Ingrese su credencial asignada");
        }
        if (txtCodigoGerencia.getText().equals("") || txtCodigoGerencia.getText() == null || txtCodigoGerencia.getText().equals(" ")) {
            txtCodigoGerencia.setText("Ingrese el codigo entregado por gerencia");
        }
        if (txtCedula.getText().equals("Ingresa tu cedula"))
            txtCedula.setText("");
    }//GEN-LAST:event_txtCedulaMousePressed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered
        setColor(btnRegistrar);
    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        resetColor(btnRegistrar);
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void btnRegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMousePressed

    }//GEN-LAST:event_btnRegistrarMousePressed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        if (txtCedula.getText().equals("") || txtCedula.getText() == null || txtCedula.getText().equals(" ")) {
            txtCedula.setText("Ingresa tu cedula");
        }
        if (txtApellido.getText().equals("") || txtApellido.getText() == null || txtApellido.getText().equals(" ")) {
            txtApellido.setText("Ingrese el apellido paterno");
        }
        if (String.valueOf(txtPassword.getPassword()).equals("") || txtPassword.getPassword() == null || String.valueOf(txtPassword.getPassword()).equals(" ")) {
            txtPassword.setText("********************");
        }
        if (txtTelefono.getText().equals("") || txtTelefono.getText() == null || txtTelefono.getText().equals(" ")) {
            txtTelefono.setText("Ingrese un número telefónico");
        }
        if (txtCorreo.getText().equals("") || txtCorreo.getText() == null || txtCorreo.getText().equals(" ")) {
            txtCorreo.setText("Ingrese el correo electronico");
        }
        if (txtCredencial.getText().equals("") || txtCredencial.getText() == null || txtCredencial.getText().equals(" ")) {
            txtCredencial.setText("Ingrese su credencial asignada");
        }
        if (txtCodigoGerencia.getText().equals("") || txtCodigoGerencia.getText() == null || txtCodigoGerencia.getText().equals(" ")) {
            txtCodigoGerencia.setText("Ingrese el codigo entregado por gerencia");
        }
        if (txtNombre.getText().equals("Ingrese el nombre"))
            txtNombre.setText("");
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed
        if (txtNombre.getText().equals("") || txtNombre.getText() == null || txtNombre.getText().equals(" ")) {
            txtNombre.setText("Ingrese el nombre");
        }
        if (txtCedula.getText().equals("") || txtCedula.getText() == null || txtCedula.getText().equals(" ")) {
            txtCedula.setText("Ingresa tu cedula");
        }
        if (String.valueOf(txtPassword.getPassword()).equals("") || txtPassword.getPassword() == null || String.valueOf(txtPassword.getPassword()).equals(" ")) {
            txtPassword.setText("********************");
        }
        if (txtTelefono.getText().equals("") || txtTelefono.getText() == null || txtTelefono.getText().equals(" ")) {
            txtTelefono.setText("Ingrese un número telefónico");
        }
        if (txtCorreo.getText().equals("") || txtCorreo.getText() == null || txtCorreo.getText().equals(" ")) {
            txtCorreo.setText("Ingrese el correo electronico");
        }
        if (txtCredencial.getText().equals("") || txtCredencial.getText() == null || txtCredencial.getText().equals(" ")) {
            txtCredencial.setText("Ingrese su credencial asignada");
        }
        if (txtCodigoGerencia.getText().equals("") || txtCodigoGerencia.getText() == null || txtCodigoGerencia.getText().equals(" ")) {
            txtCodigoGerencia.setText("Ingrese el codigo entregado por gerencia");
        }
        if (txtApellido.getText().equals("Ingrese el apellido paterno"))
            txtApellido.setText("");
    }//GEN-LAST:event_txtApellidoMousePressed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
        if (txtNombre.getText().equals("") || txtNombre.getText() == null || txtNombre.getText().equals(" ")) {
            txtNombre.setText("Ingrese el nombre");
        }
        if (txtCedula.getText().equals("") || txtCedula.getText() == null || txtCedula.getText().equals(" ")) {
            txtCedula.setText("Ingresa tu cedula");
        }
        if (txtApellido.getText().equals("") || txtApellido.getText() == null || txtApellido.getText().equals(" ")) {
            txtApellido.setText("Ingrese el apellido paterno");
        }
        if (txtTelefono.getText().equals("") || txtTelefono.getText() == null || txtTelefono.getText().equals(" ")) {
            txtTelefono.setText("Ingrese un número telefónico");
        }
        if (String.valueOf(txtPassword.getPassword()).equals("") || txtPassword.getPassword() == null || String.valueOf(txtPassword.getPassword()).equals(" ")) {
            txtPassword.setText("********************");
        }
        if (txtCredencial.getText().equals("") || txtCredencial.getText() == null || txtCredencial.getText().equals(" ")) {
            txtCredencial.setText("Ingrese su credencial asignada");
        }
        if (txtCodigoGerencia.getText().equals("") || txtCodigoGerencia.getText() == null || txtCodigoGerencia.getText().equals(" ")) {
            txtCodigoGerencia.setText("Ingrese el codigo entregado por gerencia");
        }
        if (txtCorreo.getText().equals("Ingrese el correo electronico"))
            txtCorreo.setText("");
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtCredencialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCredencialMousePressed
        // TODO add your handling code here:
        if (txtNombre.getText().equals("") || txtNombre.getText() == null || txtNombre.getText().equals(" ")) {
            txtNombre.setText("Ingrese el nombre");
        }
        if (txtCedula.getText().equals("") || txtCedula.getText() == null || txtCedula.getText().equals(" ")) {
            txtCedula.setText("Ingresa tu cedula");
        }
        if (txtApellido.getText().equals("") || txtApellido.getText() == null || txtApellido.getText().equals(" ")) {
            txtApellido.setText("Ingrese el apellido paterno");
        }
        if (txtTelefono.getText().equals("") || txtTelefono.getText() == null || txtTelefono.getText().equals(" ")) {
            txtTelefono.setText("Ingrese un número telefónico");
        }
        if (txtCorreo.getText().equals("") || txtCorreo.getText() == null || txtCorreo.getText().equals(" ")) {
            txtCorreo.setText("Ingrese el correo electronico");
        }
        if (txtCodigoGerencia.getText().equals("") || txtCodigoGerencia.getText() == null || txtCodigoGerencia.getText().equals(" ")) {
            txtCodigoGerencia.setText("Ingrese el codigo entregado por gerencia");
        }
        if (String.valueOf(txtPassword.getPassword()).equals("") || txtPassword.getPassword() == null || String.valueOf(txtPassword.getPassword()).equals(" ")) {
            txtPassword.setText("********************");
        }
        if (txtCredencial.getText().equals("Ingrese su credencial asignada"))
            txtCredencial.setText("");
    }//GEN-LAST:event_txtCredencialMousePressed

    private void txtCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCredencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCredencialActionPerformed

    private void txtCodigoGerenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoGerenciaMousePressed
        // TODO add your handling code here:
        if (txtNombre.getText().equals("") || txtNombre.getText() == null || txtNombre.getText().equals(" ")) {
            txtNombre.setText("Ingrese el nombre");
        }
        if (txtCedula.getText().equals("") || txtCedula.getText() == null || txtCedula.getText().equals(" ")) {
            txtCedula.setText("Ingresa tu cedula");
        }
        if (txtApellido.getText().equals("") || txtApellido.getText() == null || txtApellido.getText().equals(" ")) {
            txtApellido.setText("Ingrese el apellido paterno");
        }
        if (txtTelefono.getText().equals("") || txtTelefono.getText() == null || txtTelefono.getText().equals(" ")) {
            txtTelefono.setText("Ingrese un número telefónico");
        }
        if (txtCorreo.getText().equals("") || txtCorreo.getText() == null || txtCorreo.getText().equals(" ")) {
            txtCorreo.setText("Ingrese el correo electronico");
        }
        if (txtCredencial.getText().equals("") || txtCredencial.getText() == null || txtCredencial.getText().equals(" ")) {
            txtCredencial.setText("Ingrese su credencial asignada");
        }
        if (String.valueOf(txtPassword.getPassword()).equals("") || txtPassword.getPassword() == null || String.valueOf(txtPassword.getPassword()).equals(" ")) {
            txtPassword.setText("********************");
        }
        if (txtCodigoGerencia.getText().equals("Ingrese el codigo entregado por gerencia"))
            txtCodigoGerencia.setText("");
    }//GEN-LAST:event_txtCodigoGerenciaMousePressed

    private void txtCodigoGerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoGerenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoGerenciaActionPerformed

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMousePressed

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        // TODO add your handling code here:
        btnCerrar.setBackground(Color.red);
        txtCerrar.setForeground(Color.white);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        // TODO add your handling code here:
        btnCerrar.setBackground(Color.white);
        txtCerrar.setForeground(Color.black);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if ((caracter < 'A' || caracter > 'Z') && (caracter < 'a' || caracter > 'z'))
            evt.consume();
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if ((caracter < 'A' || caracter > 'Z') && (caracter < 'a' || caracter > 'z'))
            evt.consume();
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < 'A' || caracter > 'Z') && (caracter < 'a' || caracter > 'z') && (caracter < '0' || caracter > '9') && caracter == '@' && caracter == '.'))
            evt.consume();
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        if (txtCedula.getText().length() == 10) {
            evt.consume();
        } else {
            char caracter = evt.getKeyChar();
            if (caracter < '0' || caracter > '9') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        if (txtTelefono.getText().length() == 10) {
            evt.consume();
        } else {
            char caracter = evt.getKeyChar();
            if (caracter < '0' || caracter > '9') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtCredencialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCredencialKeyTyped
        // TODO add your handling code here:
        if (txtCredencial.getText().length() == 13) {
            evt.consume();
        } else {
            char caracter = evt.getKeyChar();
            if (caracter < '0' || caracter > '9') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtCredencialKeyTyped

    private void txtCodigoGerenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoGerenciaKeyTyped
        // TODO add your handling code here:
        if (txtCodigoGerencia.getText().length() == 4) {
            evt.consume();
        } else {
            char caracter = evt.getKeyChar();
            if (caracter < '0' || caracter > '9') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtCodigoGerenciaKeyTyped

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        if (verificarVacio(txtNombre.getText())) {
            lbl_avisoNombre.setVisible(true);
        } else {
            lbl_avisoNombre.setVisible(false);
        }
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyReleased
        // TODO add your handling code here:
        if (verificarVacio(txtApellido.getText())) {
            lbl_avisoApellido.setVisible(true);
        } else {
            lbl_avisoApellido.setVisible(false);
        }
    }//GEN-LAST:event_txtApellidoKeyReleased

    private void txtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyReleased
        // TODO add your handling code here:
        if (EmailValidator.getInstance().isValid(txtCorreo.getText())) {
            lbl_avisoCorreo.setVisible(false);
        } else {
            lbl_avisoCorreo.setVisible(true);
        }
    }//GEN-LAST:event_txtCorreoKeyReleased

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased
        // TODO add your handling code here:
        if (verificarCedulaTelefono(txtCedula.getText())) {
            lbl_avisoCedula.setVisible(false);
        } else {
            lbl_avisoCedula.setVisible(true);
        }
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        // TODO add your handling code here:
        if (verificarCedulaTelefono(txtTelefono.getText())) {
            lbl_avisoTelefono.setVisible(false);
        } else {
            lbl_avisoTelefono.setVisible(true);
        }
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtCredencialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCredencialKeyReleased
        // TODO add your handling code here:
        if (verificarCredencial(txtCredencial.getText())) {
            lbl_avisoCredencial.setVisible(false);
        } else {
            lbl_avisoCredencial.setVisible(true);
        }
    }//GEN-LAST:event_txtCredencialKeyReleased

    private void txtCodigoGerenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoGerenciaKeyReleased
        // TODO add your handling code here:
        if (verificarCodigo(txtCodigoGerencia.getText())) {
            lbl_avisoCodigo.setVisible(false);
        } else {
            lbl_avisoCodigo.setVisible(true);
        }
    }//GEN-LAST:event_txtCodigoGerenciaKeyReleased

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        login.lt = lt;
        login.usu=usu;
        login.denuncia=denuncia;
        login.denuncias=denuncias;
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        Login login = new Login ();
                String tipo = (String)cmbTipo.getSelectedItem();
                boolean validezCorreo = lt.buscarCorreo(txtCorreo.getText());
                boolean validezCedula = lt.buscarCedula(txtCedula.getText());
                if(tipo.equals("Comun")&&!verificarVacio(txtNombre.getText()) && !verificarVacio(txtApellido.getText()) &&  !verificar_Clave(txtCorreo.getText()) && EmailValidator.getInstance().isValid(txtCorreo.getText())
                && verificarCedulaTelefono(txtTelefono.getText()) && verificarCedulaTelefono(txtCedula.getText())){
                
                if(validezCorreo==false&&validezCedula==false){
                
                Usuario usuComun = new Usuario(txtNombre.getText(),txtApellido.getText(), txtCedula.getText(), txtPassword.getText(), txtTelefono.getText(), txtCorreo.getText(), (String)cmbTipo.getSelectedItem(), colacpusu);
                lt.agregarUsuario(usuComun);
                JOptionPane.showMessageDialog(null, "USUARIO REGISTRADO CORRECTAMENTE");
                login.lt=lt;
                login.denuncia=denuncia;
                login.denuncias=denuncias;
                login.colaabg = colaabg;
                login.colacpusu = colacpusu;
                login.setVisible(true);
                this.dispose();
                
                } else{
                        JOptionPane.showMessageDialog(null, "USUARIO YA REGISTRADO");
                    }
                
        }else if(tipo.equals("Abogado") &&!verificarVacio(txtNombre.getText()) && !verificarVacio(txtApellido.getText()) &&  !verificar_Clave(txtCorreo.getText()) && EmailValidator.getInstance().isValid(txtCorreo.getText())
                && verificarCedulaTelefono(txtTelefono.getText()) && verificarCedulaTelefono(txtCedula.getText()) && verificarCredencial(txtCredencial.getText()) && verificarCodigo(txtCodigoGerencia.getText())){
            
                if(validezCorreo==false&&validezCedula==false){
                Usuario usuAbg = new Usuario(txtNombre.getText(),txtApellido.getText(), txtCedula.getText(), txtPassword.getText(), txtTelefono.getText(), txtCorreo.getText(), (String)cmbTipo.getSelectedItem(), txtCredencial.getSelectedText(), txtCodigoGerencia.getSelectedText() , "Disponible", colaabg);
                lt.agregarUsuario(usuAbg);
                JOptionPane.showMessageDialog(null, "USUARIO REGISTRADO CORRECTAMENTE");
                login.lt=lt;
                login.denuncia=denuncia;
                login.denuncias=denuncias;
                login.colaabg = colaabg;
                login.colacpusu = colacpusu;
                login.setVisible(true);
                this.dispose();
            }
            }else{
                JOptionPane.showMessageDialog(null, "DATOS INCORRECTOS, \tVuelva a ingresar");
           }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void txtPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMousePressed
        // TODO add your handling code here:
        if (txtNombre.getText().equals("") || txtNombre.getText() == null || txtNombre.getText().equals(" ")) {
            txtNombre.setText("Ingrese el nombre");
        }
        if (txtCedula.getText().equals("") || txtCedula.getText() == null || txtCedula.getText().equals(" ")) {
            txtCedula.setText("Ingresa tu cedula");
        }
        if (txtApellido.getText().equals("") || txtApellido.getText() == null || txtApellido.getText().equals(" ")) {
            txtApellido.setText("Ingrese el apellido paterno");
        }
        if (txtTelefono.getText().equals("") || txtTelefono.getText() == null || txtTelefono.getText().equals(" ")) {
            txtTelefono.setText("Ingrese un número telefónico");
        }
        if (txtCorreo.getText().equals("") || txtCorreo.getText() == null || txtCorreo.getText().equals(" ")) {
            txtCorreo.setText("Ingrese el correo electronico");
        }
        if (txtCredencial.getText().equals("") || txtCredencial.getText() == null || txtCredencial.getText().equals(" ")) {
            txtCredencial.setText("Ingrese su credencial asignada");
        }
        if (txtCodigoGerencia.getText().equals("") || txtCodigoGerencia.getText() == null || txtCodigoGerencia.getText().equals(" ")) {
            txtCodigoGerencia.setText("Ingrese el codigo entregado por gerencia");
        }
        if (String.valueOf(txtPassword.getPassword()).equals("********************"))
            txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordMousePressed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
                String tipo = (String) cmbTipo.getSelectedItem();
        if (tipo.equals("Seleccionar")) {
            txtNombre.setEnabled(false);
            txtApellido.setEnabled(false);
            txtCedula.setEnabled(false);
            txtCorreo.setEnabled(false);
            txtPassword.setEnabled(false);
            txtTelefono.setEnabled(false);
            txtCodigoGerencia.setEnabled(false);
            txtCredencial.setEnabled(false);
            btnRegistrar.setEnabled(false);
        }
        if (tipo.equals("Comun")) {
            txtCredencial.setVisible(false);
            txtCodigoGerencia.setVisible(false);
            txtNombre.setEnabled(true);
            txtApellido.setEnabled(true);
            txtCedula.setEnabled(true);
            txtCorreo.setEnabled(true);
            txtPassword.setEnabled(true);
            txtTelefono.setEnabled(true);
            txtCodigoGerencia.setEnabled(true);
            txtCredencial.setEnabled(true);
            btnRegistrar.setEnabled(true);
            lblCodigoGerencia.setVisible(false);
            lblCredencial.setVisible(false);
            jSeparator8.setVisible(false);
            jSeparator9.setVisible(false);
        }
        if (tipo.equals("Abogado")) {
            txtCredencial.setVisible(true);
            txtCodigoGerencia.setVisible(true);
            txtNombre.setEnabled(true);
            txtApellido.setEnabled(true);
            txtCedula.setEnabled(true);
            txtCorreo.setEnabled(true);
            txtPassword.setEnabled(true);
            txtTelefono.setEnabled(true);
            txtCodigoGerencia.setEnabled(true);
            txtCredencial.setEnabled(true);
            btnRegistrar.setEnabled(true);
            lblCodigoGerencia.setVisible(true);
            lblCredencial.setVisible(true);
            jSeparator8.setVisible(true);
            jSeparator9.setVisible(true);
        }
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void datosQuemadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datosQuemadosMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);

        Usuario comun = new Usuario("Kevin","Rosero", "1004177455", "Gordito21xd.", "0993884541", "kevin.rosero@udla.edu.ec", "Comun", colacpusu);
        Usuario comun1 = new Usuario ("Alex","Ayala", "1000000000", "A123456789.", "0993884544", "alex.ayala@cidhu.org.es", "Comun", colacpusu);
        Usuario presidente = new Usuario ("admin", "admin", "admin@cidhu.org.es","1004177454", colatotal,"Presidente" );
        Usuario abogado = new Usuario ("Aaron","Rosero", "1004177433", "A123456789.", "0993884541", "aron.rosero@udla.edu.ec", "Abogado","1004177433004","0401","Disponible", colaabg);
        
        lt.agregarUsuario(comun);
                lt.agregarUsuario(comun1);
        lt.agregarUsuario(presidente);
        lt.agregarUsuario(abogado);

        login.lt = lt;
        login.denuncia=denuncia;
        login.denuncias=denuncias;
        login.colacpusu=colacpusu;
        login.colatotal=colatotal;
        login.colaabg = colaabg;
        
        this.dispose();
    }//GEN-LAST:event_datosQuemadosMouseClicked

    private void datosQuemadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosQuemadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datosQuemadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    void setColor(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnCerrar;
    private javax.swing.JPanel btnRegistrar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JButton datosQuemados;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblCodigoGerencia;
    private javax.swing.JLabel lblCredencial;
    private javax.swing.JLabel lbl_avisoApellido;
    private javax.swing.JLabel lbl_avisoCedula;
    private javax.swing.JLabel lbl_avisoClave;
    private javax.swing.JLabel lbl_avisoCodigo;
    private javax.swing.JLabel lbl_avisoCorreo;
    private javax.swing.JLabel lbl_avisoCredencial;
    private javax.swing.JLabel lbl_avisoNombre;
    private javax.swing.JLabel lbl_avisoTelefono;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JLabel txtCerrar;
    private javax.swing.JTextField txtCodigoGerencia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCredencial;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
